// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/mpc/v1/mpc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用的 Admin 鉴权 Token
type AdminAuthToken struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReqId             string                 `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`                                     // 请求ID (防重放)
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // Admin 用户ID
	PasskeySignature  []byte                 `protobuf:"bytes,3,opt,name=passkey_signature,json=passkeySignature,proto3" json:"passkey_signature,omitempty"`    // assertion signature
	AuthenticatorData []byte                 `protobuf:"bytes,4,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"` // authData
	ClientDataJson    []byte                 `protobuf:"bytes,5,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`        // clientDataJSON
	CredentialId      string                 `protobuf:"bytes,6,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`                // credential ID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminAuthToken) Reset() {
	*x = AdminAuthToken{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuthToken) ProtoMessage() {}

func (x *AdminAuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuthToken.ProtoReflect.Descriptor instead.
func (*AdminAuthToken) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{0}
}

func (x *AdminAuthToken) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *AdminAuthToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminAuthToken) GetPasskeySignature() []byte {
	if x != nil {
		return x.PasskeySignature
	}
	return nil
}

func (x *AdminAuthToken) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *AdminAuthToken) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *AdminAuthToken) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

// 管理相关消息
type SetSigningPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PolicyType    string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"` // "single", "team"
	MinSignatures int32                  `protobuf:"varint,3,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	AdminAuth     *AdminAuthToken        `protobuf:"bytes,4,opt,name=admin_auth,json=adminAuth,proto3" json:"admin_auth,omitempty"` // Admin 鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSigningPolicyRequest) Reset() {
	*x = SetSigningPolicyRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSigningPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSigningPolicyRequest) ProtoMessage() {}

func (x *SetSigningPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSigningPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetSigningPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{1}
}

func (x *SetSigningPolicyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SetSigningPolicyRequest) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *SetSigningPolicyRequest) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

func (x *SetSigningPolicyRequest) GetAdminAuth() *AdminAuthToken {
	if x != nil {
		return x.AdminAuth
	}
	return nil
}

type SetSigningPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSigningPolicyResponse) Reset() {
	*x = SetSigningPolicyResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSigningPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSigningPolicyResponse) ProtoMessage() {}

func (x *SetSigningPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSigningPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetSigningPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{2}
}

func (x *SetSigningPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetSigningPolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSigningPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningPolicyRequest) Reset() {
	*x = GetSigningPolicyRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningPolicyRequest) ProtoMessage() {}

func (x *GetSigningPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetSigningPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetSigningPolicyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetSigningPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PolicyType    string                 `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	MinSignatures int32                  `protobuf:"varint,3,opt,name=min_signatures,json=minSignatures,proto3" json:"min_signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningPolicyResponse) Reset() {
	*x = GetSigningPolicyResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningPolicyResponse) ProtoMessage() {}

func (x *GetSigningPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetSigningPolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetSigningPolicyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetSigningPolicyResponse) GetPolicyType() string {
	if x != nil {
		return x.PolicyType
	}
	return ""
}

func (x *GetSigningPolicyResponse) GetMinSignatures() int32 {
	if x != nil {
		return x.MinSignatures
	}
	return 0
}

type AddUserPasskeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"` // WebAuthn Credential ID
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`          // COSE Key Format (Hex or Base64)
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 关联的用户ID
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`       // 设备名称
	AdminAuth     *AdminAuthToken        `protobuf:"bytes,5,opt,name=admin_auth,json=adminAuth,proto3" json:"admin_auth,omitempty"`          // Admin 鉴权 (或用户自签名)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserPasskeyRequest) Reset() {
	*x = AddUserPasskeyRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserPasskeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPasskeyRequest) ProtoMessage() {}

func (x *AddUserPasskeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPasskeyRequest.ProtoReflect.Descriptor instead.
func (*AddUserPasskeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{5}
}

func (x *AddUserPasskeyRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *AddUserPasskeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AddUserPasskeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddUserPasskeyRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AddUserPasskeyRequest) GetAdminAuth() *AdminAuthToken {
	if x != nil {
		return x.AdminAuth
	}
	return nil
}

type AddUserPasskeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserPasskeyResponse) Reset() {
	*x = AddUserPasskeyResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserPasskeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserPasskeyResponse) ProtoMessage() {}

func (x *AddUserPasskeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserPasskeyResponse.ProtoReflect.Descriptor instead.
func (*AddUserPasskeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{6}
}

func (x *AddUserPasskeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddUserPasskeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 会话相关消息
type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message          []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Protocol         string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "gg18", "gg20", "frost"
	TimeoutSeconds   int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ParticipantNodes []string               `protobuf:"bytes,5,rep,name=participant_nodes,json=participantNodes,proto3" json:"participant_nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSessionRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateSessionRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateSessionRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateSessionRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetParticipantNodes() []string {
	if x != nil {
		return x.ParticipantNodes
	}
	return nil
}

type CreateSessionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Threshold          int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes         int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSessionResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateSessionResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *CreateSessionResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{9}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentRound       int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds        int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	Signature          string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // hex encoded
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs         int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{10}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SessionStatusResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *SessionStatusResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *SessionStatusResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SessionStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 协议消息请求
type SubmitProtocolMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProtocolMessageRequest) Reset() {
	*x = SubmitProtocolMessageRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProtocolMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProtocolMessageRequest) ProtoMessage() {}

func (x *SubmitProtocolMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProtocolMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitProtocolMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitProtocolMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitProtocolMessageRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubmitProtocolMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubmitProtocolMessageRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SubmitProtocolMessageRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 协议消息响应
type SubmitProtocolMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextRound     int32                  `protobuf:"varint,3,opt,name=next_round,json=nextRound,proto3" json:"next_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProtocolMessageResponse) Reset() {
	*x = SubmitProtocolMessageResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProtocolMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProtocolMessageResponse) ProtoMessage() {}

func (x *SubmitProtocolMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProtocolMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitProtocolMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitProtocolMessageResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitProtocolMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitProtocolMessageResponse) GetNextRound() int32 {
	if x != nil {
		return x.NextRound
	}
	return 0
}

// 启动 DKG 请求/响应
type StartDKGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // DKG 会话ID（等于 key_id）
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // 例：ECDSA
	Curve         string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`         // 例：secp256k1
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds       []string               `protobuf:"bytes,7,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`       // 参与节点列表
	AdminAuth     *AdminAuthToken        `protobuf:"bytes,8,opt,name=admin_auth,json=adminAuth,proto3" json:"admin_auth,omitempty"` // Admin 鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDKGRequest) Reset() {
	*x = StartDKGRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGRequest) ProtoMessage() {}

func (x *StartDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGRequest.ProtoReflect.Descriptor instead.
func (*StartDKGRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{13}
}

func (x *StartDKGRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartDKGRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartDKGRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StartDKGRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *StartDKGRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartDKGRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartDKGRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *StartDKGRequest) GetAdminAuth() *AdminAuthToken {
	if x != nil {
		return x.AdminAuth
	}
	return nil
}

type StartDKGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDKGResponse) Reset() {
	*x = StartDKGResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGResponse) ProtoMessage() {}

func (x *StartDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGResponse.ProtoReflect.Descriptor instead.
func (*StartDKGResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{14}
}

func (x *StartDKGResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartDKGResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 启动签名 请求/响应
type StartSignRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	SessionId       string                        `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 签名会话ID
	KeyId           string                        `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message         []byte                        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // 要签名的消息
	MessageHex      string                        `protobuf:"bytes,4,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"` // 消息的hex编码（可选）
	Protocol        string                        `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                       // "gg18", "gg20", "frost"
	Threshold       int32                         `protobuf:"varint,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes      int32                         `protobuf:"varint,7,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds         []string                      `protobuf:"bytes,8,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`                            // 参与节点列表
	DerivationPath  string                        `protobuf:"bytes,9,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`       // 派生路径 (e.g. "m/44'/60'/0'/0/0")
	ParentChainCode []byte                        `protobuf:"bytes,10,opt,name=parent_chain_code,json=parentChainCode,proto3" json:"parent_chain_code,omitempty"` // 根 ChainCode，用于派生
	AuthTokens      []*StartSignRequest_AuthToken `protobuf:"bytes,11,rep,name=auth_tokens,json=authTokens,proto3" json:"auth_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartSignRequest) Reset() {
	*x = StartSignRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest) ProtoMessage() {}

func (x *StartSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest.ProtoReflect.Descriptor instead.
func (*StartSignRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{15}
}

func (x *StartSignRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartSignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StartSignRequest) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *StartSignRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StartSignRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartSignRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartSignRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *StartSignRequest) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *StartSignRequest) GetParentChainCode() []byte {
	if x != nil {
		return x.ParentChainCode
	}
	return nil
}

func (x *StartSignRequest) GetAuthTokens() []*StartSignRequest_AuthToken {
	if x != nil {
		return x.AuthTokens
	}
	return nil
}

type StartSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignResponse) Reset() {
	*x = StartSignResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignResponse) ProtoMessage() {}

func (x *StartSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignResponse.ProtoReflect.Descriptor instead.
func (*StartSignResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{16}
}

func (x *StartSignResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartSignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 启动密钥轮换 请求/响应
type StartResharingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`      // 会话ID (通常等于 key_id)
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                  // 目标密钥ID
	OldNodeIds    []string               `protobuf:"bytes,3,rep,name=old_node_ids,json=oldNodeIds,proto3" json:"old_node_ids,omitempty"` // 旧参与节点列表
	NewNodeIds    []string               `protobuf:"bytes,4,rep,name=new_node_ids,json=newNodeIds,proto3" json:"new_node_ids,omitempty"` // 新参与节点列表
	OldThreshold  int32                  `protobuf:"varint,5,opt,name=old_threshold,json=oldThreshold,proto3" json:"old_threshold,omitempty"`
	NewThreshold  int32                  `protobuf:"varint,6,opt,name=new_threshold,json=newThreshold,proto3" json:"new_threshold,omitempty"`
	AdminAuth     *AdminAuthToken        `protobuf:"bytes,7,opt,name=admin_auth,json=adminAuth,proto3" json:"admin_auth,omitempty"` // Admin 鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResharingRequest) Reset() {
	*x = StartResharingRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResharingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResharingRequest) ProtoMessage() {}

func (x *StartResharingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResharingRequest.ProtoReflect.Descriptor instead.
func (*StartResharingRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{17}
}

func (x *StartResharingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartResharingRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartResharingRequest) GetOldNodeIds() []string {
	if x != nil {
		return x.OldNodeIds
	}
	return nil
}

func (x *StartResharingRequest) GetNewNodeIds() []string {
	if x != nil {
		return x.NewNodeIds
	}
	return nil
}

func (x *StartResharingRequest) GetOldThreshold() int32 {
	if x != nil {
		return x.OldThreshold
	}
	return 0
}

func (x *StartResharingRequest) GetNewThreshold() int32 {
	if x != nil {
		return x.NewThreshold
	}
	return 0
}

func (x *StartResharingRequest) GetAdminAuth() *AdminAuthToken {
	if x != nil {
		return x.AdminAuth
	}
	return nil
}

type StartResharingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResharingResponse) Reset() {
	*x = StartResharingResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResharingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResharingResponse) ProtoMessage() {}

func (x *StartResharingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResharingResponse.ProtoReflect.Descriptor instead.
func (*StartResharingResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{18}
}

func (x *StartResharingResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartResharingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 签名聚合相关消息
type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{19}
}

func (x *AggregateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // hex encoded
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex encoded
	MessageHash   string                 `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	AggregatedAt  string                 `protobuf:"bytes,5,opt,name=aggregated_at,json=aggregatedAt,proto3" json:"aggregated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{20}
}

func (x *AggregateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AggregateResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AggregateResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AggregateResponse) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

func (x *AggregateResponse) GetAggregatedAt() string {
	if x != nil {
		return x.AggregatedAt
	}
	return ""
}

// 心跳消息
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SentAt        string                 `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	StatusInfo    map[string]string      `protobuf:"bytes,3,rep,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *HeartbeatRequest) GetStatusInfo() map[string]string {
	if x != nil {
		return x.StatusInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Instructions  map[string]string      `protobuf:"bytes,4,rep,name=instructions,proto3" json:"instructions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *HeartbeatResponse) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *HeartbeatResponse) GetInstructions() map[string]string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// 鉴权令牌列表
type StartSignRequest_AuthToken struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // 签名者用户ID
	PasskeySignature  []byte                 `protobuf:"bytes,2,opt,name=passkey_signature,json=passkeySignature,proto3" json:"passkey_signature,omitempty"`    // WebAuthn Assertion Signature
	AuthenticatorData []byte                 `protobuf:"bytes,3,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"` // WebAuthn AuthData
	ClientDataJson    []byte                 `protobuf:"bytes,4,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`        // WebAuthn ClientDataJSON
	CredentialId      string                 `protobuf:"bytes,5,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`                // WebAuthn Credential ID
	// 兼容字段 (可保留或废弃)
	PublicKey     string `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	MemberId      string `protobuf:"bytes,8,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignRequest_AuthToken) Reset() {
	*x = StartSignRequest_AuthToken{}
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest_AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest_AuthToken) ProtoMessage() {}

func (x *StartSignRequest_AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mpc_v1_mpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest_AuthToken.ProtoReflect.Descriptor instead.
func (*StartSignRequest_AuthToken) Descriptor() ([]byte, []int) {
	return file_proto_mpc_v1_mpc_proto_rawDescGZIP(), []int{15, 0}
}

func (x *StartSignRequest_AuthToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartSignRequest_AuthToken) GetPasskeySignature() []byte {
	if x != nil {
		return x.PasskeySignature
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *StartSignRequest_AuthToken) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *StartSignRequest_AuthToken) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_proto_mpc_v1_mpc_proto protoreflect.FileDescriptor

const file_proto_mpc_v1_mpc_proto_rawDesc = "" +
	"\n" +
	"\x16proto/mpc/v1/mpc.proto\x12\x06mpc.v1\"\xeb\x01\n" +
	"\x0eAdminAuthToken\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\tR\x05reqId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x11passkey_signature\x18\x03 \x01(\fR\x10passkeySignature\x12-\n" +
	"\x12authenticator_data\x18\x04 \x01(\fR\x11authenticatorData\x12(\n" +
	"\x10client_data_json\x18\x05 \x01(\fR\x0eclientDataJson\x12#\n" +
	"\rcredential_id\x18\x06 \x01(\tR\fcredentialId\"\xaf\x01\n" +
	"\x17SetSigningPolicyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12%\n" +
	"\x0emin_signatures\x18\x03 \x01(\x05R\rminSignatures\x125\n" +
	"\n" +
	"admin_auth\x18\x04 \x01(\v2\x16.mpc.v1.AdminAuthTokenR\tadminAuth\"N\n" +
	"\x18SetSigningPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x17GetSigningPolicyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"y\n" +
	"\x18GetSigningPolicyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vpolicy_type\x18\x02 \x01(\tR\n" +
	"policyType\x12%\n" +
	"\x0emin_signatures\x18\x03 \x01(\x05R\rminSignatures\"\xcc\x01\n" +
	"\x15AddUserPasskeyRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x125\n" +
	"\n" +
	"admin_auth\x18\x05 \x01(\v2\x16.mpc.v1.AdminAuthTokenR\tadminAuth\"L\n" +
	"\x16AddUserPasskeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x14CreateSessionRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11participant_nodes\x18\x05 \x03(\tR\x10participantNodes\"\xfc\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc8\x02\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\"\x9e\x01\n" +
	"\x1cSubmitProtocolMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"t\n" +
	"\x1dSubmitProtocolMessageResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"next_round\x18\x03 \x01(\x05R\tnextRound\"\x8c\x02\n" +
	"\x0fStartDKGRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\a \x03(\tR\anodeIds\x125\n" +
	"\n" +
	"admin_auth\x18\b \x01(\v2\x16.mpc.v1.AdminAuthTokenR\tadminAuth\"F\n" +
	"\x10StartDKGResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbf\x05\n" +
	"\x10StartSignRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1f\n" +
	"\vmessage_hex\x18\x04 \x01(\tR\n" +
	"messageHex\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x06 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\a \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\b \x03(\tR\anodeIds\x12'\n" +
	"\x0fderivation_path\x18\t \x01(\tR\x0ederivationPath\x12*\n" +
	"\x11parent_chain_code\x18\n" +
	" \x01(\fR\x0fparentChainCode\x12C\n" +
	"\vauth_tokens\x18\v \x03(\v2\".mpc.v1.StartSignRequest.AuthTokenR\n" +
	"authTokens\x1a\xa9\x02\n" +
	"\tAuthToken\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11passkey_signature\x18\x02 \x01(\fR\x10passkeySignature\x12-\n" +
	"\x12authenticator_data\x18\x03 \x01(\fR\x11authenticatorData\x12(\n" +
	"\x10client_data_json\x18\x04 \x01(\fR\x0eclientDataJson\x12#\n" +
	"\rcredential_id\x18\x05 \x01(\tR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1b\n" +
	"\tmember_id\x18\b \x01(\tR\bmemberId\"G\n" +
	"\x11StartSignResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x02\n" +
	"\x15StartResharingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12 \n" +
	"\fold_node_ids\x18\x03 \x03(\tR\n" +
	"oldNodeIds\x12 \n" +
	"\fnew_node_ids\x18\x04 \x03(\tR\n" +
	"newNodeIds\x12#\n" +
	"\rold_threshold\x18\x05 \x01(\x05R\foldThreshold\x12#\n" +
	"\rnew_threshold\x18\x06 \x01(\x05R\fnewThreshold\x125\n" +
	"\n" +
	"admin_auth\x18\a \x01(\v2\x16.mpc.v1.AdminAuthTokenR\tadminAuth\"L\n" +
	"\x16StartResharingResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x10AggregateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb2\x01\n" +
	"\x11AggregateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12!\n" +
	"\fmessage_hash\x18\x04 \x01(\tR\vmessageHash\x12#\n" +
	"\raggregated_at\x18\x05 \x01(\tR\faggregatedAt\"\xce\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\tR\x06sentAt\x12I\n" +
	"\vstatus_info\x18\x03 \x03(\v2(.mpc.v1.HeartbeatRequest.StatusInfoEntryR\n" +
	"statusInfo\x1a=\n" +
	"\x0fStatusInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\tR\n" +
	"receivedAt\x12O\n" +
	"\finstructions\x18\x04 \x03(\v2+.mpc.v1.HeartbeatResponse.InstructionsEntryR\finstructions\x1a?\n" +
	"\x11InstructionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x83\x03\n" +
	"\aMPCNode\x12d\n" +
	"\x15SubmitProtocolMessage\x12$.mpc.v1.SubmitProtocolMessageRequest\x1a%.mpc.v1.SubmitProtocolMessageResponse\x12=\n" +
	"\bStartDKG\x12\x17.mpc.v1.StartDKGRequest\x1a\x18.mpc.v1.StartDKGResponse\x12@\n" +
	"\tStartSign\x12\x18.mpc.v1.StartSignRequest\x1a\x19.mpc.v1.StartSignResponse\x12O\n" +
	"\x0eStartResharing\x12\x1d.mpc.v1.StartResharingRequest\x1a\x1e.mpc.v1.StartResharingResponse\x12@\n" +
	"\tHeartbeat\x12\x18.mpc.v1.HeartbeatRequest\x1a\x19.mpc.v1.HeartbeatResponse2\x82\x02\n" +
	"\x0eMPCCoordinator\x12S\n" +
	"\x14CreateSigningSession\x12\x1c.mpc.v1.CreateSessionRequest\x1a\x1d.mpc.v1.CreateSessionResponse\x12O\n" +
	"\x10GetSessionStatus\x12\x1c.mpc.v1.SessionStatusRequest\x1a\x1d.mpc.v1.SessionStatusResponse\x12J\n" +
	"\x13AggregateSignatures\x12\x18.mpc.v1.AggregateRequest\x1a\x19.mpc.v1.AggregateResponse2\x8e\x02\n" +
	"\rMPCManagement\x12U\n" +
	"\x10SetSigningPolicy\x12\x1f.mpc.v1.SetSigningPolicyRequest\x1a .mpc.v1.SetSigningPolicyResponse\x12U\n" +
	"\x10GetSigningPolicy\x12\x1f.mpc.v1.GetSigningPolicyRequest\x1a .mpc.v1.GetSigningPolicyResponse\x12O\n" +
	"\x0eAddUserPasskey\x12\x1d.mpc.v1.AddUserPasskeyRequest\x1a\x1e.mpc.v1.AddUserPasskeyResponseB6Z4github.com/kashguard/go-mpc-infra/mpc/v1b\x06proto3"

var (
	file_proto_mpc_v1_mpc_proto_rawDescOnce sync.Once
	file_proto_mpc_v1_mpc_proto_rawDescData []byte
)

func file_proto_mpc_v1_mpc_proto_rawDescGZIP() []byte {
	file_proto_mpc_v1_mpc_proto_rawDescOnce.Do(func() {
		file_proto_mpc_v1_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_mpc_proto_rawDesc), len(file_proto_mpc_v1_mpc_proto_rawDesc)))
	})
	return file_proto_mpc_v1_mpc_proto_rawDescData
}

var file_proto_mpc_v1_mpc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_mpc_v1_mpc_proto_goTypes = []any{
	(*AdminAuthToken)(nil),                // 0: mpc.v1.AdminAuthToken
	(*SetSigningPolicyRequest)(nil),       // 1: mpc.v1.SetSigningPolicyRequest
	(*SetSigningPolicyResponse)(nil),      // 2: mpc.v1.SetSigningPolicyResponse
	(*GetSigningPolicyRequest)(nil),       // 3: mpc.v1.GetSigningPolicyRequest
	(*GetSigningPolicyResponse)(nil),      // 4: mpc.v1.GetSigningPolicyResponse
	(*AddUserPasskeyRequest)(nil),         // 5: mpc.v1.AddUserPasskeyRequest
	(*AddUserPasskeyResponse)(nil),        // 6: mpc.v1.AddUserPasskeyResponse
	(*CreateSessionRequest)(nil),          // 7: mpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),         // 8: mpc.v1.CreateSessionResponse
	(*SessionStatusRequest)(nil),          // 9: mpc.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil),         // 10: mpc.v1.SessionStatusResponse
	(*SubmitProtocolMessageRequest)(nil),  // 11: mpc.v1.SubmitProtocolMessageRequest
	(*SubmitProtocolMessageResponse)(nil), // 12: mpc.v1.SubmitProtocolMessageResponse
	(*StartDKGRequest)(nil),               // 13: mpc.v1.StartDKGRequest
	(*StartDKGResponse)(nil),              // 14: mpc.v1.StartDKGResponse
	(*StartSignRequest)(nil),              // 15: mpc.v1.StartSignRequest
	(*StartSignResponse)(nil),             // 16: mpc.v1.StartSignResponse
	(*StartResharingRequest)(nil),         // 17: mpc.v1.StartResharingRequest
	(*StartResharingResponse)(nil),        // 18: mpc.v1.StartResharingResponse
	(*AggregateRequest)(nil),              // 19: mpc.v1.AggregateRequest
	(*AggregateResponse)(nil),             // 20: mpc.v1.AggregateResponse
	(*HeartbeatRequest)(nil),              // 21: mpc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 22: mpc.v1.HeartbeatResponse
	(*StartSignRequest_AuthToken)(nil),    // 23: mpc.v1.StartSignRequest.AuthToken
	nil,                                   // 24: mpc.v1.HeartbeatRequest.StatusInfoEntry
	nil,                                   // 25: mpc.v1.HeartbeatResponse.InstructionsEntry
}
var file_proto_mpc_v1_mpc_proto_depIdxs = []int32{
	0,  // 0: mpc.v1.SetSigningPolicyRequest.admin_auth:type_name -> mpc.v1.AdminAuthToken
	0,  // 1: mpc.v1.AddUserPasskeyRequest.admin_auth:type_name -> mpc.v1.AdminAuthToken
	0,  // 2: mpc.v1.StartDKGRequest.admin_auth:type_name -> mpc.v1.AdminAuthToken
	23, // 3: mpc.v1.StartSignRequest.auth_tokens:type_name -> mpc.v1.StartSignRequest.AuthToken
	0,  // 4: mpc.v1.StartResharingRequest.admin_auth:type_name -> mpc.v1.AdminAuthToken
	24, // 5: mpc.v1.HeartbeatRequest.status_info:type_name -> mpc.v1.HeartbeatRequest.StatusInfoEntry
	25, // 6: mpc.v1.HeartbeatResponse.instructions:type_name -> mpc.v1.HeartbeatResponse.InstructionsEntry
	11, // 7: mpc.v1.MPCNode.SubmitProtocolMessage:input_type -> mpc.v1.SubmitProtocolMessageRequest
	13, // 8: mpc.v1.MPCNode.StartDKG:input_type -> mpc.v1.StartDKGRequest
	15, // 9: mpc.v1.MPCNode.StartSign:input_type -> mpc.v1.StartSignRequest
	17, // 10: mpc.v1.MPCNode.StartResharing:input_type -> mpc.v1.StartResharingRequest
	21, // 11: mpc.v1.MPCNode.Heartbeat:input_type -> mpc.v1.HeartbeatRequest
	7,  // 12: mpc.v1.MPCCoordinator.CreateSigningSession:input_type -> mpc.v1.CreateSessionRequest
	9,  // 13: mpc.v1.MPCCoordinator.GetSessionStatus:input_type -> mpc.v1.SessionStatusRequest
	19, // 14: mpc.v1.MPCCoordinator.AggregateSignatures:input_type -> mpc.v1.AggregateRequest
	1,  // 15: mpc.v1.MPCManagement.SetSigningPolicy:input_type -> mpc.v1.SetSigningPolicyRequest
	3,  // 16: mpc.v1.MPCManagement.GetSigningPolicy:input_type -> mpc.v1.GetSigningPolicyRequest
	5,  // 17: mpc.v1.MPCManagement.AddUserPasskey:input_type -> mpc.v1.AddUserPasskeyRequest
	12, // 18: mpc.v1.MPCNode.SubmitProtocolMessage:output_type -> mpc.v1.SubmitProtocolMessageResponse
	14, // 19: mpc.v1.MPCNode.StartDKG:output_type -> mpc.v1.StartDKGResponse
	16, // 20: mpc.v1.MPCNode.StartSign:output_type -> mpc.v1.StartSignResponse
	18, // 21: mpc.v1.MPCNode.StartResharing:output_type -> mpc.v1.StartResharingResponse
	22, // 22: mpc.v1.MPCNode.Heartbeat:output_type -> mpc.v1.HeartbeatResponse
	8,  // 23: mpc.v1.MPCCoordinator.CreateSigningSession:output_type -> mpc.v1.CreateSessionResponse
	10, // 24: mpc.v1.MPCCoordinator.GetSessionStatus:output_type -> mpc.v1.SessionStatusResponse
	20, // 25: mpc.v1.MPCCoordinator.AggregateSignatures:output_type -> mpc.v1.AggregateResponse
	2,  // 26: mpc.v1.MPCManagement.SetSigningPolicy:output_type -> mpc.v1.SetSigningPolicyResponse
	4,  // 27: mpc.v1.MPCManagement.GetSigningPolicy:output_type -> mpc.v1.GetSigningPolicyResponse
	6,  // 28: mpc.v1.MPCManagement.AddUserPasskey:output_type -> mpc.v1.AddUserPasskeyResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_mpc_v1_mpc_proto_init() }
func file_proto_mpc_v1_mpc_proto_init() {
	if File_proto_mpc_v1_mpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mpc_v1_mpc_proto_rawDesc), len(file_proto_mpc_v1_mpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_mpc_v1_mpc_proto_goTypes,
		DependencyIndexes: file_proto_mpc_v1_mpc_proto_depIdxs,
		MessageInfos:      file_proto_mpc_v1_mpc_proto_msgTypes,
	}.Build()
	File_proto_mpc_v1_mpc_proto = out.File
	file_proto_mpc_v1_mpc_proto_goTypes = nil
	file_proto_mpc_v1_mpc_proto_depIdxs = nil
}
