// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AddWalletMemberPayload add wallet member payload
//
// swagger:model addWalletMemberPayload
type AddWalletMemberPayload struct {

	// admin auths
	// Required: true
	AdminAuths []*AdminAuthToken `json:"admin_auths"`

	// credential id
	// Example: cred-new-member
	// Required: true
	CredentialID *string `json:"credential_id"`

	// role
	// Example: member
	// Required: true
	// Enum: [admin member]
	Role *string `json:"role"`
}

// Validate validates this add wallet member payload
func (m *AddWalletMemberPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdminAuths(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentialID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddWalletMemberPayload) validateAdminAuths(formats strfmt.Registry) error {

	if err := validate.Required("admin_auths", "body", m.AdminAuths); err != nil {
		return err
	}

	for i := 0; i < len(m.AdminAuths); i++ {
		if swag.IsZero(m.AdminAuths[i]) { // not required
			continue
		}

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AddWalletMemberPayload) validateCredentialID(formats strfmt.Registry) error {

	if err := validate.Required("credential_id", "body", m.CredentialID); err != nil {
		return err
	}

	return nil
}

var addWalletMemberPayloadTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["admin","member"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		addWalletMemberPayloadTypeRolePropEnum = append(addWalletMemberPayloadTypeRolePropEnum, v)
	}
}

const (

	// AddWalletMemberPayloadRoleAdmin captures enum value "admin"
	AddWalletMemberPayloadRoleAdmin string = "admin"

	// AddWalletMemberPayloadRoleMember captures enum value "member"
	AddWalletMemberPayloadRoleMember string = "member"
)

// prop value enum
func (m *AddWalletMemberPayload) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, addWalletMemberPayloadTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AddWalletMemberPayload) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this add wallet member payload based on the context it is used
func (m *AddWalletMemberPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdminAuths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AddWalletMemberPayload) contextValidateAdminAuths(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdminAuths); i++ {

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AddWalletMemberPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddWalletMemberPayload) UnmarshalBinary(b []byte) error {
	var res AddWalletMemberPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
