// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AdminAuthToken admin auth token
//
// swagger:model adminAuthToken
type AdminAuthToken struct {

	// authenticator data
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	AuthenticatorData *strfmt.Base64 `json:"authenticator_data"`

	// client data json
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	ClientDataJSON *strfmt.Base64 `json:"client_data_json"`

	// credential id
	// Example: cred-xyz
	// Required: true
	CredentialID *string `json:"credential_id"`

	// passkey signature
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	PasskeySignature *strfmt.Base64 `json:"passkey_signature"`

	// req id
	// Example: req-123
	ReqID string `json:"req_id,omitempty"`
}

// Validate validates this admin auth token
func (m *AdminAuthToken) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthenticatorData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientDataJSON(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentialID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePasskeySignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdminAuthToken) validateAuthenticatorData(formats strfmt.Registry) error {

	if err := validate.Required("authenticator_data", "body", m.AuthenticatorData); err != nil {
		return err
	}

	return nil
}

func (m *AdminAuthToken) validateClientDataJSON(formats strfmt.Registry) error {

	if err := validate.Required("client_data_json", "body", m.ClientDataJSON); err != nil {
		return err
	}

	return nil
}

func (m *AdminAuthToken) validateCredentialID(formats strfmt.Registry) error {

	if err := validate.Required("credential_id", "body", m.CredentialID); err != nil {
		return err
	}

	return nil
}

func (m *AdminAuthToken) validatePasskeySignature(formats strfmt.Registry) error {

	if err := validate.Required("passkey_signature", "body", m.PasskeySignature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this admin auth token based on context it is used
func (m *AdminAuthToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdminAuthToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdminAuthToken) UnmarshalBinary(b []byte) error {
	var res AdminAuthToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
