// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateKeyResponse create key response
//
// swagger:model createKeyResponse
type CreateKeyResponse struct {

	// address
	// Example: addr-0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb
	Address string `json:"address,omitempty"`

	// algorithm
	// Example: ECDSA
	// Required: true
	Algorithm *string `json:"algorithm"`

	// chain type
	// Example: ethereum
	// Required: true
	ChainType *string `json:"chain_type"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// curve
	// Example: secp256k1
	// Required: true
	Curve *string `json:"curve"`

	// description
	Description string `json:"description,omitempty"`

	// key id
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// public key
	// Example: pub-0x1234567890abcdef...
	// Required: true
	PublicKey *string `json:"public_key"`

	// status
	// Example: Active
	// Required: true
	// Enum: [Active Inactive PendingDeletion Deleted]
	Status *string `json:"status"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`

	// threshold
	// Example: 2
	// Required: true
	Threshold *int64 `json:"threshold"`

	// total nodes
	// Example: 3
	// Required: true
	TotalNodes *int64 `json:"total_nodes"`
}

// Validate validates this create key response
func (m *CreateKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurve(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalNodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateKeyResponse) validateAlgorithm(formats strfmt.Registry) error {

	if err := validate.Required("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateCurve(formats strfmt.Registry) error {

	if err := validate.Required("curve", "body", m.Curve); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

var createKeyResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Active","Inactive","PendingDeletion","Deleted"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createKeyResponseTypeStatusPropEnum = append(createKeyResponseTypeStatusPropEnum, v)
	}
}

const (

	// CreateKeyResponseStatusActive captures enum value "Active"
	CreateKeyResponseStatusActive string = "Active"

	// CreateKeyResponseStatusInactive captures enum value "Inactive"
	CreateKeyResponseStatusInactive string = "Inactive"

	// CreateKeyResponseStatusPendingDeletion captures enum value "PendingDeletion"
	CreateKeyResponseStatusPendingDeletion string = "PendingDeletion"

	// CreateKeyResponseStatusDeleted captures enum value "Deleted"
	CreateKeyResponseStatusDeleted string = "Deleted"
)

// prop value enum
func (m *CreateKeyResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createKeyResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateKeyResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateThreshold(formats strfmt.Registry) error {

	if err := validate.Required("threshold", "body", m.Threshold); err != nil {
		return err
	}

	return nil
}

func (m *CreateKeyResponse) validateTotalNodes(formats strfmt.Registry) error {

	if err := validate.Required("total_nodes", "body", m.TotalNodes); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create key response based on context it is used
func (m *CreateKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateKeyResponse) UnmarshalBinary(b []byte) error {
	var res CreateKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
