// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GenerateAddressResponse generate address response
//
// swagger:model generateAddressResponse
type GenerateAddressResponse struct {

	// address
	// Example: 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb
	// Required: true
	Address *string `json:"address"`

	// chain type
	// Example: ethereum
	// Required: true
	ChainType *string `json:"chain_type"`

	// key id
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`
}

// Validate validates this generate address response
func (m *GenerateAddressResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GenerateAddressResponse) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *GenerateAddressResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *GenerateAddressResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this generate address response based on context it is used
func (m *GenerateAddressResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GenerateAddressResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GenerateAddressResponse) UnmarshalBinary(b []byte) error {
	var res GenerateAddressResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
