// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetNodeResponse get node response
//
// swagger:model getNodeResponse
type GetNodeResponse struct {

	// capabilities
	Capabilities []string `json:"capabilities"`

	// endpoint
	// Required: true
	Endpoint *string `json:"endpoint"`

	// last heartbeat
	// Format: date-time
	LastHeartbeat strfmt.DateTime `json:"last_heartbeat,omitempty"`

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`

	// node id
	// Required: true
	NodeID *string `json:"node_id"`

	// node type
	// Required: true
	NodeType *string `json:"node_type"`

	// public key
	PublicKey string `json:"public_key,omitempty"`

	// registered at
	// Format: date-time
	RegisteredAt strfmt.DateTime `json:"registered_at,omitempty"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this get node response
func (m *GetNodeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastHeartbeat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegisteredAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetNodeResponse) validateEndpoint(formats strfmt.Registry) error {

	if err := validate.Required("endpoint", "body", m.Endpoint); err != nil {
		return err
	}

	return nil
}

func (m *GetNodeResponse) validateLastHeartbeat(formats strfmt.Registry) error {
	if swag.IsZero(m.LastHeartbeat) { // not required
		return nil
	}

	if err := validate.FormatOf("last_heartbeat", "body", "date-time", m.LastHeartbeat.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetNodeResponse) validateNodeID(formats strfmt.Registry) error {

	if err := validate.Required("node_id", "body", m.NodeID); err != nil {
		return err
	}

	return nil
}

func (m *GetNodeResponse) validateNodeType(formats strfmt.Registry) error {

	if err := validate.Required("node_type", "body", m.NodeType); err != nil {
		return err
	}

	return nil
}

func (m *GetNodeResponse) validateRegisteredAt(formats strfmt.Registry) error {
	if swag.IsZero(m.RegisteredAt) { // not required
		return nil
	}

	if err := validate.FormatOf("registered_at", "body", "date-time", m.RegisteredAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetNodeResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get node response based on context it is used
func (m *GetNodeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetNodeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNodeResponse) UnmarshalBinary(b []byte) error {
	var res GetNodeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
