// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSessionResponse get session response
//
// swagger:model getSessionResponse
type GetSessionResponse struct {

	// completed at
	// Format: date-time
	CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// current round
	CurrentRound int64 `json:"current_round,omitempty"`

	// duration ms
	DurationMs int64 `json:"duration_ms,omitempty"`

	// key id
	// Required: true
	KeyID *string `json:"key_id"`

	// participating nodes
	ParticipatingNodes []string `json:"participating_nodes"`

	// protocol
	// Required: true
	Protocol *string `json:"protocol"`

	// session id
	// Required: true
	SessionID *string `json:"session_id"`

	// signature
	Signature string `json:"signature,omitempty"`

	// status
	// Required: true
	Status *string `json:"status"`

	// threshold
	Threshold int64 `json:"threshold,omitempty"`

	// total nodes
	TotalNodes int64 `json:"total_nodes,omitempty"`

	// total rounds
	TotalRounds int64 `json:"total_rounds,omitempty"`
}

// Validate validates this get session response
func (m *GetSessionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionResponse) validateCompletedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CompletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("completed_at", "body", "date-time", m.CompletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateProtocol(formats strfmt.Registry) error {

	if err := validate.Required("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("session_id", "body", m.SessionID); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get session response based on context it is used
func (m *GetSessionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionResponse) UnmarshalBinary(b []byte) error {
	var res GetSessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
