// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostSignPayload post sign payload
//
// swagger:model postSignPayload
type PostSignPayload struct {

	// chain type
	// Example: ethereum
	ChainType string `json:"chain_type,omitempty"`

	// key id
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// message
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// message type
	// Example: transaction
	// Enum: [transaction message raw]
	MessageType string `json:"message_type,omitempty"`
}

// Validate validates this post sign payload
func (m *PostSignPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessageType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostSignPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostSignPayload) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var postSignPayloadTypeMessageTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["transaction","message","raw"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postSignPayloadTypeMessageTypePropEnum = append(postSignPayloadTypeMessageTypePropEnum, v)
	}
}

const (

	// PostSignPayloadMessageTypeTransaction captures enum value "transaction"
	PostSignPayloadMessageTypeTransaction string = "transaction"

	// PostSignPayloadMessageTypeMessage captures enum value "message"
	PostSignPayloadMessageTypeMessage string = "message"

	// PostSignPayloadMessageTypeRaw captures enum value "raw"
	PostSignPayloadMessageTypeRaw string = "raw"
)

// prop value enum
func (m *PostSignPayload) validateMessageTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postSignPayloadTypeMessageTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostSignPayload) validateMessageType(formats strfmt.Registry) error {
	if swag.IsZero(m.MessageType) { // not required
		return nil
	}

	// value enum
	if err := m.validateMessageTypeEnum("message_type", "body", m.MessageType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post sign payload based on context it is used
func (m *PostSignPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostSignPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostSignPayload) UnmarshalBinary(b []byte) error {
	var res PostSignPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
