// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostWebAuthnRegisterBeginPayload post web authn register begin payload
//
// swagger:model postWebAuthnRegisterBeginPayload
type PostWebAuthnRegisterBeginPayload struct {

	// 显示名称
	// Example: John Doe
	DisplayName string `json:"display_name,omitempty"`

	// 用户唯一标识
	// Example: user-123
	// Required: true
	UserID *string `json:"user_id"`

	// 用户名（通常是邮箱）
	// Example: john@example.com
	// Required: true
	UserName *string `json:"user_name"`
}

// Validate validates this post web authn register begin payload
func (m *PostWebAuthnRegisterBeginPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostWebAuthnRegisterBeginPayload) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

func (m *PostWebAuthnRegisterBeginPayload) validateUserName(formats strfmt.Registry) error {

	if err := validate.Required("user_name", "body", m.UserName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post web authn register begin payload based on context it is used
func (m *PostWebAuthnRegisterBeginPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostWebAuthnRegisterBeginPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostWebAuthnRegisterBeginPayload) UnmarshalBinary(b []byte) error {
	var res PostWebAuthnRegisterBeginPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
