// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostRegisterNodePayload post register node payload
//
// swagger:model postRegisterNodePayload
type PostRegisterNodePayload struct {

	// capabilities
	// Example: ["gg18","gg20"]
	Capabilities []string `json:"capabilities"`

	// endpoint
	// Example: https://node-1.example.com:8080
	// Required: true
	Endpoint *string `json:"endpoint"`

	// metadata
	Metadata map[string]string `json:"metadata,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// node type
	// Example: participant
	// Required: true
	// Enum: [coordinator participant]
	NodeType *string `json:"node_type"`

	// public key
	// Example: pub-0x1234567890abcdef...
	// Required: true
	PublicKey *string `json:"public_key"`
}

// Validate validates this post register node payload
func (m *PostRegisterNodePayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostRegisterNodePayload) validateEndpoint(formats strfmt.Registry) error {

	if err := validate.Required("endpoint", "body", m.Endpoint); err != nil {
		return err
	}

	return nil
}

var postRegisterNodePayloadTypeNodeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["coordinator","participant"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postRegisterNodePayloadTypeNodeTypePropEnum = append(postRegisterNodePayloadTypeNodeTypePropEnum, v)
	}
}

const (

	// PostRegisterNodePayloadNodeTypeCoordinator captures enum value "coordinator"
	PostRegisterNodePayloadNodeTypeCoordinator string = "coordinator"

	// PostRegisterNodePayloadNodeTypeParticipant captures enum value "participant"
	PostRegisterNodePayloadNodeTypeParticipant string = "participant"
)

// prop value enum
func (m *PostRegisterNodePayload) validateNodeTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postRegisterNodePayloadTypeNodeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostRegisterNodePayload) validateNodeType(formats strfmt.Registry) error {

	if err := validate.Required("node_type", "body", m.NodeType); err != nil {
		return err
	}

	// value enum
	if err := m.validateNodeTypeEnum("node_type", "body", *m.NodeType); err != nil {
		return err
	}

	return nil
}

func (m *PostRegisterNodePayload) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post register node payload based on context it is used
func (m *PostRegisterNodePayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostRegisterNodePayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostRegisterNodePayload) UnmarshalBinary(b []byte) error {
	var res PostRegisterNodePayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
