// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostVerifyPayload post verify payload
//
// swagger:model postVerifyPayload
type PostVerifyPayload struct {

	// algorithm
	// Example: ECDSA
	// Enum: [ECDSA EdDSA]
	Algorithm string `json:"algorithm,omitempty"`

	// chain type
	// Example: ethereum
	ChainType string `json:"chain_type,omitempty"`

	// message
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// public key
	// Example: pub-0x1234567890abcdef...
	// Required: true
	PublicKey *string `json:"public_key"`

	// signature
	// Example: 0x1234567890abcdef...
	// Required: true
	Signature *string `json:"signature"`
}

// Validate validates this post verify payload
func (m *PostVerifyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postVerifyPayloadTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECDSA","EdDSA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postVerifyPayloadTypeAlgorithmPropEnum = append(postVerifyPayloadTypeAlgorithmPropEnum, v)
	}
}

const (

	// PostVerifyPayloadAlgorithmECDSA captures enum value "ECDSA"
	PostVerifyPayloadAlgorithmECDSA string = "ECDSA"

	// PostVerifyPayloadAlgorithmEdDSA captures enum value "EdDSA"
	PostVerifyPayloadAlgorithmEdDSA string = "EdDSA"
)

// prop value enum
func (m *PostVerifyPayload) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postVerifyPayloadTypeAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostVerifyPayload) validateAlgorithm(formats strfmt.Registry) error {
	if swag.IsZero(m.Algorithm) { // not required
		return nil
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *PostVerifyPayload) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post verify payload based on context it is used
func (m *PostVerifyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostVerifyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostVerifyPayload) UnmarshalBinary(b []byte) error {
	var res PostVerifyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
