// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateSessionPayload post create session payload
//
// swagger:model postCreateSessionPayload
type PostCreateSessionPayload struct {

	// key id
	// Required: true
	KeyID *string `json:"key_id"`

	// message
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// protocol
	// Example: gg20
	// Enum: [gg18 gg20 frost]
	Protocol string `json:"protocol,omitempty"`

	// timeout
	// Example: 300
	Timeout int64 `json:"timeout,omitempty"`
}

// Validate validates this post create session payload
func (m *PostCreateSessionPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateSessionPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateSessionPayload) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var postCreateSessionPayloadTypeProtocolPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["gg18","gg20","frost"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateSessionPayloadTypeProtocolPropEnum = append(postCreateSessionPayloadTypeProtocolPropEnum, v)
	}
}

const (

	// PostCreateSessionPayloadProtocolGg18 captures enum value "gg18"
	PostCreateSessionPayloadProtocolGg18 string = "gg18"

	// PostCreateSessionPayloadProtocolGg20 captures enum value "gg20"
	PostCreateSessionPayloadProtocolGg20 string = "gg20"

	// PostCreateSessionPayloadProtocolFrost captures enum value "frost"
	PostCreateSessionPayloadProtocolFrost string = "frost"
)

// prop value enum
func (m *PostCreateSessionPayload) validateProtocolEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateSessionPayloadTypeProtocolPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateSessionPayload) validateProtocol(formats strfmt.Registry) error {
	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtocolEnum("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create session payload based on context it is used
func (m *PostCreateSessionPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateSessionPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateSessionPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateSessionPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
