// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostBatchSignPayload post batch sign payload
//
// swagger:model postBatchSignPayload
type PostBatchSignPayload struct {

	// chain type
	// Example: ethereum
	ChainType string `json:"chain_type,omitempty"`

	// key id
	// Example: key-1234567890abcdef
	// Required: true
	KeyID *string `json:"key_id"`

	// messages
	// Required: true
	Messages []*PostBatchSignPayloadMessagesItems0 `json:"messages"`
}

// Validate validates this post batch sign payload
func (m *PostBatchSignPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostBatchSignPayload) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *PostBatchSignPayload) validateMessages(formats strfmt.Registry) error {

	if err := validate.Required("messages", "body", m.Messages); err != nil {
		return err
	}

	for i := 0; i < len(m.Messages); i++ {
		if swag.IsZero(m.Messages[i]) { // not required
			continue
		}

		if m.Messages[i] != nil {
			if err := m.Messages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("messages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this post batch sign payload based on the context it is used
func (m *PostBatchSignPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMessages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostBatchSignPayload) contextValidateMessages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Messages); i++ {

		if m.Messages[i] != nil {
			if err := m.Messages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("messages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostBatchSignPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostBatchSignPayload) UnmarshalBinary(b []byte) error {
	var res PostBatchSignPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PostBatchSignPayloadMessagesItems0 post batch sign payload messages items0
//
// swagger:model PostBatchSignPayloadMessagesItems0
type PostBatchSignPayloadMessagesItems0 struct {

	// message
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Message *strfmt.Base64 `json:"message"`

	// message type
	// Example: transaction
	// Enum: [transaction message raw]
	MessageType string `json:"message_type,omitempty"`
}

// Validate validates this post batch sign payload messages items0
func (m *PostBatchSignPayloadMessagesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessageType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostBatchSignPayloadMessagesItems0) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var postBatchSignPayloadMessagesItems0TypeMessageTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["transaction","message","raw"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postBatchSignPayloadMessagesItems0TypeMessageTypePropEnum = append(postBatchSignPayloadMessagesItems0TypeMessageTypePropEnum, v)
	}
}

const (

	// PostBatchSignPayloadMessagesItems0MessageTypeTransaction captures enum value "transaction"
	PostBatchSignPayloadMessagesItems0MessageTypeTransaction string = "transaction"

	// PostBatchSignPayloadMessagesItems0MessageTypeMessage captures enum value "message"
	PostBatchSignPayloadMessagesItems0MessageTypeMessage string = "message"

	// PostBatchSignPayloadMessagesItems0MessageTypeRaw captures enum value "raw"
	PostBatchSignPayloadMessagesItems0MessageTypeRaw string = "raw"
)

// prop value enum
func (m *PostBatchSignPayloadMessagesItems0) validateMessageTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postBatchSignPayloadMessagesItems0TypeMessageTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostBatchSignPayloadMessagesItems0) validateMessageType(formats strfmt.Registry) error {
	if swag.IsZero(m.MessageType) { // not required
		return nil
	}

	// value enum
	if err := m.validateMessageTypeEnum("message_type", "body", m.MessageType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post batch sign payload messages items0 based on context it is used
func (m *PostBatchSignPayloadMessagesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostBatchSignPayloadMessagesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostBatchSignPayloadMessagesItems0) UnmarshalBinary(b []byte) error {
	var res PostBatchSignPayloadMessagesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
