// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateKeyPayload post create key payload
//
// swagger:model postCreateKeyPayload
type PostCreateKeyPayload struct {

	// algorithm
	// Example: ECDSA
	// Required: true
	// Enum: [ECDSA EdDSA]
	Algorithm *string `json:"algorithm"`

	// chain type
	// Example: ethereum
	// Required: true
	// Enum: [bitcoin ethereum bsc avalanche]
	ChainType *string `json:"chain_type"`

	// curve
	// Example: secp256k1
	// Required: true
	// Enum: [secp256k1 secp256r1 Ed25519]
	Curve *string `json:"curve"`

	// description
	// Example: 企业多签钱包密钥
	Description string `json:"description,omitempty"`

	// tags
	// Example: {"environment":"production","wallet_type":"multisig"}
	Tags map[string]string `json:"tags,omitempty"`

	// threshold
	// Example: 2
	// Required: true
	// Minimum: 2
	Threshold *int64 `json:"threshold"`

	// total nodes
	// Example: 3
	// Required: true
	// Minimum: 2
	TotalNodes *int64 `json:"total_nodes"`
}

// Validate validates this post create key payload
func (m *PostCreateKeyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurve(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalNodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postCreateKeyPayloadTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECDSA","EdDSA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateKeyPayloadTypeAlgorithmPropEnum = append(postCreateKeyPayloadTypeAlgorithmPropEnum, v)
	}
}

const (

	// PostCreateKeyPayloadAlgorithmECDSA captures enum value "ECDSA"
	PostCreateKeyPayloadAlgorithmECDSA string = "ECDSA"

	// PostCreateKeyPayloadAlgorithmEdDSA captures enum value "EdDSA"
	PostCreateKeyPayloadAlgorithmEdDSA string = "EdDSA"
)

// prop value enum
func (m *PostCreateKeyPayload) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateKeyPayloadTypeAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateKeyPayload) validateAlgorithm(formats strfmt.Registry) error {

	if err := validate.Required("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", *m.Algorithm); err != nil {
		return err
	}

	return nil
}

var postCreateKeyPayloadTypeChainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["bitcoin","ethereum","bsc","avalanche"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateKeyPayloadTypeChainTypePropEnum = append(postCreateKeyPayloadTypeChainTypePropEnum, v)
	}
}

const (

	// PostCreateKeyPayloadChainTypeBitcoin captures enum value "bitcoin"
	PostCreateKeyPayloadChainTypeBitcoin string = "bitcoin"

	// PostCreateKeyPayloadChainTypeEthereum captures enum value "ethereum"
	PostCreateKeyPayloadChainTypeEthereum string = "ethereum"

	// PostCreateKeyPayloadChainTypeBsc captures enum value "bsc"
	PostCreateKeyPayloadChainTypeBsc string = "bsc"

	// PostCreateKeyPayloadChainTypeAvalanche captures enum value "avalanche"
	PostCreateKeyPayloadChainTypeAvalanche string = "avalanche"
)

// prop value enum
func (m *PostCreateKeyPayload) validateChainTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateKeyPayloadTypeChainTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateKeyPayload) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	// value enum
	if err := m.validateChainTypeEnum("chain_type", "body", *m.ChainType); err != nil {
		return err
	}

	return nil
}

var postCreateKeyPayloadTypeCurvePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["secp256k1","secp256r1","Ed25519"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateKeyPayloadTypeCurvePropEnum = append(postCreateKeyPayloadTypeCurvePropEnum, v)
	}
}

const (

	// PostCreateKeyPayloadCurveSecp256k1 captures enum value "secp256k1"
	PostCreateKeyPayloadCurveSecp256k1 string = "secp256k1"

	// PostCreateKeyPayloadCurveSecp256r1 captures enum value "secp256r1"
	PostCreateKeyPayloadCurveSecp256r1 string = "secp256r1"

	// PostCreateKeyPayloadCurveEd25519 captures enum value "Ed25519"
	PostCreateKeyPayloadCurveEd25519 string = "Ed25519"
)

// prop value enum
func (m *PostCreateKeyPayload) validateCurveEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateKeyPayloadTypeCurvePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateKeyPayload) validateCurve(formats strfmt.Registry) error {

	if err := validate.Required("curve", "body", m.Curve); err != nil {
		return err
	}

	// value enum
	if err := m.validateCurveEnum("curve", "body", *m.Curve); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateKeyPayload) validateThreshold(formats strfmt.Registry) error {

	if err := validate.Required("threshold", "body", m.Threshold); err != nil {
		return err
	}

	if err := validate.MinimumInt("threshold", "body", *m.Threshold, 2, false); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateKeyPayload) validateTotalNodes(formats strfmt.Registry) error {

	if err := validate.Required("total_nodes", "body", m.TotalNodes); err != nil {
		return err
	}

	if err := validate.MinimumInt("total_nodes", "body", *m.TotalNodes, 2, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create key payload based on context it is used
func (m *PostCreateKeyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateKeyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateKeyPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateKeyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
