// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostWebAuthnLoginBeginPayload post web authn login begin payload
//
// swagger:model postWebAuthnLoginBeginPayload
type PostWebAuthnLoginBeginPayload struct {

	// user id
	// Example: user-123
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this post web authn login begin payload
func (m *PostWebAuthnLoginBeginPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostWebAuthnLoginBeginPayload) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post web authn login begin payload based on context it is used
func (m *PostWebAuthnLoginBeginPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostWebAuthnLoginBeginPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostWebAuthnLoginBeginPayload) UnmarshalBinary(b []byte) error {
	var res PostWebAuthnLoginBeginPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
