// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostWebAuthnLoginFinishPayload post web authn login finish payload
//
// swagger:model postWebAuthnLoginFinishPayload
type PostWebAuthnLoginFinishPayload struct {

	// 前端 navigator.credentials.get() 的返回结果
	// Required: true
	Response interface{} `json:"response"`

	// 从 begin 接口返回的 session_data
	// Required: true
	SessionData *string `json:"session_data"`

	// user id
	// Example: user-123
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this post web authn login finish payload
func (m *PostWebAuthnLoginFinishPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResponse(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostWebAuthnLoginFinishPayload) validateResponse(formats strfmt.Registry) error {

	if m.Response == nil {
		return errors.Required("response", "body", nil)
	}

	return nil
}

func (m *PostWebAuthnLoginFinishPayload) validateSessionData(formats strfmt.Registry) error {

	if err := validate.Required("session_data", "body", m.SessionData); err != nil {
		return err
	}

	return nil
}

func (m *PostWebAuthnLoginFinishPayload) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post web authn login finish payload based on context it is used
func (m *PostWebAuthnLoginFinishPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostWebAuthnLoginFinishPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostWebAuthnLoginFinishPayload) UnmarshalBinary(b []byte) error {
	var res PostWebAuthnLoginFinishPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
