// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RemoveWalletMemberPayload remove wallet member payload
//
// swagger:model removeWalletMemberPayload
type RemoveWalletMemberPayload struct {

	// admin auths
	// Required: true
	AdminAuths []*AdminAuthToken `json:"admin_auths"`

	// credential id
	// Example: cred-to-remove
	// Required: true
	CredentialID *string `json:"credential_id"`
}

// Validate validates this remove wallet member payload
func (m *RemoveWalletMemberPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdminAuths(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentialID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoveWalletMemberPayload) validateAdminAuths(formats strfmt.Registry) error {

	if err := validate.Required("admin_auths", "body", m.AdminAuths); err != nil {
		return err
	}

	for i := 0; i < len(m.AdminAuths); i++ {
		if swag.IsZero(m.AdminAuths[i]) { // not required
			continue
		}

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RemoveWalletMemberPayload) validateCredentialID(formats strfmt.Registry) error {

	if err := validate.Required("credential_id", "body", m.CredentialID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this remove wallet member payload based on the context it is used
func (m *RemoveWalletMemberPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdminAuths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoveWalletMemberPayload) contextValidateAdminAuths(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdminAuths); i++ {

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemoveWalletMemberPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoveWalletMemberPayload) UnmarshalBinary(b []byte) error {
	var res RemoveWalletMemberPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
