// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetSigningPolicyPayload set signing policy payload
//
// swagger:model setSigningPolicyPayload
type SetSigningPolicyPayload struct {

	// admin auths
	// Required: true
	AdminAuths []*AdminAuthToken `json:"admin_auths"`

	// min signatures
	// Example: 2
	// Required: true
	// Minimum: 1
	MinSignatures *int64 `json:"min_signatures"`

	// policy type
	// Example: team
	// Required: true
	// Enum: [single team]
	PolicyType *string `json:"policy_type"`
}

// Validate validates this set signing policy payload
func (m *SetSigningPolicyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdminAuths(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinSignatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicyType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetSigningPolicyPayload) validateAdminAuths(formats strfmt.Registry) error {

	if err := validate.Required("admin_auths", "body", m.AdminAuths); err != nil {
		return err
	}

	for i := 0; i < len(m.AdminAuths); i++ {
		if swag.IsZero(m.AdminAuths[i]) { // not required
			continue
		}

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SetSigningPolicyPayload) validateMinSignatures(formats strfmt.Registry) error {

	if err := validate.Required("min_signatures", "body", m.MinSignatures); err != nil {
		return err
	}

	if err := validate.MinimumInt("min_signatures", "body", *m.MinSignatures, 1, false); err != nil {
		return err
	}

	return nil
}

var setSigningPolicyPayloadTypePolicyTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["single","team"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		setSigningPolicyPayloadTypePolicyTypePropEnum = append(setSigningPolicyPayloadTypePolicyTypePropEnum, v)
	}
}

const (

	// SetSigningPolicyPayloadPolicyTypeSingle captures enum value "single"
	SetSigningPolicyPayloadPolicyTypeSingle string = "single"

	// SetSigningPolicyPayloadPolicyTypeTeam captures enum value "team"
	SetSigningPolicyPayloadPolicyTypeTeam string = "team"
)

// prop value enum
func (m *SetSigningPolicyPayload) validatePolicyTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, setSigningPolicyPayloadTypePolicyTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SetSigningPolicyPayload) validatePolicyType(formats strfmt.Registry) error {

	if err := validate.Required("policy_type", "body", m.PolicyType); err != nil {
		return err
	}

	// value enum
	if err := m.validatePolicyTypeEnum("policy_type", "body", *m.PolicyType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this set signing policy payload based on the context it is used
func (m *SetSigningPolicyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdminAuths(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetSigningPolicyPayload) contextValidateAdminAuths(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AdminAuths); i++ {

		if m.AdminAuths[i] != nil {
			if err := m.AdminAuths[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("admin_auths" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SetSigningPolicyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetSigningPolicyPayload) UnmarshalBinary(b []byte) error {
	var res SetSigningPolicyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
