// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignResponse sign response
//
// swagger:model signResponse
type SignResponse struct {

	// chain type
	// Required: true
	ChainType *string `json:"chain_type"`

	// key id
	// Required: true
	KeyID *string `json:"key_id"`

	// message
	// Required: true
	Message *string `json:"message"`

	// participating nodes
	ParticipatingNodes []string `json:"participating_nodes"`

	// public key
	// Required: true
	PublicKey *string `json:"public_key"`

	// session id
	// Required: true
	SessionID *string `json:"session_id"`

	// signature
	// Example: sig-0x1234567890abcdef...
	// Required: true
	Signature *string `json:"signature"`

	// signed at
	// Format: date-time
	SignedAt strfmt.DateTime `json:"signed_at,omitempty"`
}

// Validate validates this sign response
func (m *SignResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("session_id", "body", m.SessionID); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

func (m *SignResponse) validateSignedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.SignedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("signed_at", "body", "date-time", m.SignedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sign response based on context it is used
func (m *SignResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignResponse) UnmarshalBinary(b []byte) error {
	var res SignResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
