// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SigningPolicyResponse signing policy response
//
// swagger:model signingPolicyResponse
type SigningPolicyResponse struct {

	// key id
	KeyID string `json:"key_id,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// min signatures
	MinSignatures int64 `json:"min_signatures,omitempty"`

	// policy type
	PolicyType string `json:"policy_type,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this signing policy response
func (m *SigningPolicyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this signing policy response based on context it is used
func (m *SigningPolicyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SigningPolicyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SigningPolicyResponse) UnmarshalBinary(b []byte) error {
	var res SigningPolicyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
