// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NewSwaggerSpec creates a new SwaggerSpec instance
func NewSwaggerSpec() *SwaggerSpec {

	spec := &SwaggerSpec{
		Handlers: make(map[string]map[string]bool),
	}

	if len(spec.Handlers) == 0 {
		spec.initHandlerCache()
	}

	return spec
}

/*SwaggerSpec API documentation */
type SwaggerSpec struct {
	Handlers map[string]map[string]bool
}

func (o *SwaggerSpec) initHandlerCache() {
	o.Handlers = make(map[string]map[string]bool)

	// https://swagger.io/specification/v2/ fixed fields: GET, PUT, POST, DELETE, OPTIONS, HEAD, PATCH
	o.Handlers["GET"] = make(map[string]bool)
	o.Handlers["PUT"] = make(map[string]bool)
	o.Handlers["POST"] = make(map[string]bool)
	o.Handlers["DELETE"] = make(map[string]bool)
	o.Handlers["OPTIONS"] = make(map[string]bool)
	o.Handlers["HEAD"] = make(map[string]bool)
	o.Handlers["PATCH"] = make(map[string]bool)

	o.Handlers["DELETE"]["/api/v1/auth/account"] = true
	o.Handlers["GET"]["/.well-known/assetlinks.json"] = true
	o.Handlers["GET"]["/.well-known/apple-app-site-association"] = true
	o.Handlers["GET"]["/api/v1/auth/register"] = true
	o.Handlers["GET"]["/-/healthy"] = true
	o.Handlers["GET"]["/-/ready"] = true
	o.Handlers["GET"]["/swagger.yml"] = true
	o.Handlers["GET"]["/api/v1/auth/userinfo"] = true
	o.Handlers["GET"]["/-/version"] = true
	o.Handlers["POST"]["/api/v1/auth/change-password"] = true
	o.Handlers["POST"]["/api/v1/auth/register/{registrationToken}"] = true
	o.Handlers["POST"]["/api/v1/auth/forgot-password/complete"] = true
	o.Handlers["POST"]["/api/v1/auth/forgot-password"] = true
	o.Handlers["POST"]["/api/v1/auth/login"] = true
	o.Handlers["POST"]["/api/v1/auth/logout"] = true
	o.Handlers["POST"]["/api/v1/auth/refresh"] = true
	o.Handlers["POST"]["/api/v1/auth/register"] = true
	o.Handlers["PUT"]["/api/v1/push/token"] = true
	o.Handlers["DELETE"]["/api/v1/mpc/keys/{keyId}"] = true
	o.Handlers["GET"]["/api/v1/mpc/keys/{keyId}"] = true
	o.Handlers["GET"]["/api/v1/mpc/keys"] = true
	o.Handlers["GET"]["/api/v1/mpc/nodes/{nodeId}"] = true
	o.Handlers["GET"]["/api/v1/mpc/nodes/{nodeId}/health"] = true
	o.Handlers["GET"]["/api/v1/mpc/nodes"] = true
	o.Handlers["GET"]["/api/v1/mpc/sessions/{sessionId}"] = true
	o.Handlers["POST"]["/api/v1/mpc/sessions/{sessionId}/cancel"] = true
	o.Handlers["POST"]["/api/v1/mpc/keys"] = true
	o.Handlers["POST"]["/api/v1/mpc/sessions"] = true
	o.Handlers["POST"]["/api/v1/mpc/keys/{keyId}/address"] = true
	o.Handlers["POST"]["/api/v1/mpc/sessions/{sessionId}/join"] = true
	o.Handlers["POST"]["/api/v1/mpc/sign/batch"] = true
	o.Handlers["POST"]["/api/v1/mpc/sign"] = true
	o.Handlers["POST"]["/api/v1/mpc/verify"] = true
	o.Handlers["POST"]["/api/v1/mpc/nodes"] = true
}
