// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebAuthnRegisterBeginResponse web authn register begin response
//
// swagger:model webAuthnRegisterBeginResponse
type WebAuthnRegisterBeginResponse struct {

	// WebAuthn CredentialCreationOptions
	// Required: true
	Options interface{} `json:"options"`

	// 会话数据（Base64URL 编码的 challenge）
	// Required: true
	SessionData *string `json:"session_data"`
}

// Validate validates this web authn register begin response
func (m *WebAuthnRegisterBeginResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebAuthnRegisterBeginResponse) validateOptions(formats strfmt.Registry) error {

	if m.Options == nil {
		return errors.Required("options", "body", nil)
	}

	return nil
}

func (m *WebAuthnRegisterBeginResponse) validateSessionData(formats strfmt.Registry) error {

	if err := validate.Required("session_data", "body", m.SessionData); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this web authn register begin response based on context it is used
func (m *WebAuthnRegisterBeginResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebAuthnRegisterBeginResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebAuthnRegisterBeginResponse) UnmarshalBinary(b []byte) error {
	var res WebAuthnRegisterBeginResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
