// Code generated by go-swagger; DO NOT EDIT.

package m_p_c_sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostJoinMpcSessionParams creates a new PostJoinMpcSessionParams object
// no default values defined in spec.
func NewPostJoinMpcSessionParams() PostJoinMpcSessionParams {

	return PostJoinMpcSessionParams{}
}

// PostJoinMpcSessionParams contains all the bound params for the post join mpc session operation
// typically these are obtained from a http.Request
//
// swagger:parameters postJoinMpcSession
type PostJoinMpcSessionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	NodeID string `query:"node_id"`
	/*
	  Required: true
	  In: path
	*/
	SessionID string `param:"sessionId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostJoinMpcSessionParams() beforehand.
func (o *PostJoinMpcSessionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qNodeID, qhkNodeID, _ := qs.GetOK("node_id")
	if err := o.bindNodeID(qNodeID, qhkNodeID, route.Formats); err != nil {
		res = append(res, err)
	}

	rSessionID, rhkSessionID, _ := route.Params.GetOK("sessionId")
	if err := o.bindSessionID(rSessionID, rhkSessionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostJoinMpcSessionParams) Validate(formats strfmt.Registry) error {
	var res []error

	// node_id
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("node_id", "query", o.NodeID); err != nil {
		res = append(res, err)
	}

	// sessionId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNodeID binds and validates parameter NodeID from query.
func (o *PostJoinMpcSessionParams) bindNodeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("node_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("node_id", "query", raw); err != nil {
		return err
	}

	o.NodeID = raw

	return nil
}

// bindSessionID binds and validates parameter SessionID from path.
func (o *PostJoinMpcSessionParams) bindSessionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.SessionID = raw

	return nil
}
