// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: mpc/v1/mpc.proto

package mpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 协议消息请求
type SubmitProtocolMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProtocolMessageRequest) Reset() {
	*x = SubmitProtocolMessageRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProtocolMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProtocolMessageRequest) ProtoMessage() {}

func (x *SubmitProtocolMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProtocolMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitProtocolMessageRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitProtocolMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitProtocolMessageRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubmitProtocolMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubmitProtocolMessageRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SubmitProtocolMessageRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 协议消息响应
type SubmitProtocolMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NextRound     int32                  `protobuf:"varint,3,opt,name=next_round,json=nextRound,proto3" json:"next_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitProtocolMessageResponse) Reset() {
	*x = SubmitProtocolMessageResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitProtocolMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitProtocolMessageResponse) ProtoMessage() {}

func (x *SubmitProtocolMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitProtocolMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitProtocolMessageResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitProtocolMessageResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitProtocolMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitProtocolMessageResponse) GetNextRound() int32 {
	if x != nil {
		return x.NextRound
	}
	return 0
}

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message          []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Protocol         string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "gg18", "gg20", "frost"
	TimeoutSeconds   int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ParticipantNodes []string               `protobuf:"bytes,5,rep,name=participant_nodes,json=participantNodes,proto3" json:"participant_nodes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateSessionRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CreateSessionRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateSessionRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetParticipantNodes() []string {
	if x != nil {
		return x.ParticipantNodes
	}
	return nil
}

type CreateSessionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Threshold          int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes         int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSessionResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateSessionResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *CreateSessionResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{4}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentRound       int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds        int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	ParticipatingNodes []string               `protobuf:"bytes,5,rep,name=participating_nodes,json=participatingNodes,proto3" json:"participating_nodes,omitempty"`
	Signature          string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // hex encoded
	CreatedAt          string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs         int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{5}
}

func (x *SessionStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStatusResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SessionStatusResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *SessionStatusResponse) GetParticipatingNodes() []string {
	if x != nil {
		return x.ParticipatingNodes
	}
	return nil
}

func (x *SessionStatusResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SessionStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *SessionStatusResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 启动 DKG 请求
type StartDKGRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // DKG 会话ID（等于 key_id）
	KeyId           string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm       string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // 例：ECDSA
	Curve           string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`         // 例：secp256k1
	Threshold       int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes      int32                  `protobuf:"varint,6,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds         []string               `protobuf:"bytes,7,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`                           // 参与节点列表
	ClientPublicKey string                 `protobuf:"bytes,8,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"` // Client (P1) 的 Passkey 公钥（hex，2-of-2 模式需要）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartDKGRequest) Reset() {
	*x = StartDKGRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGRequest) ProtoMessage() {}

func (x *StartDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGRequest.ProtoReflect.Descriptor instead.
func (*StartDKGRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{6}
}

func (x *StartDKGRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartDKGRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartDKGRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StartDKGRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *StartDKGRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartDKGRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartDKGRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *StartDKGRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

type StartDKGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDKGResponse) Reset() {
	*x = StartDKGResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDKGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDKGResponse) ProtoMessage() {}

func (x *StartDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDKGResponse.ProtoReflect.Descriptor instead.
func (*StartDKGResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{7}
}

func (x *StartDKGResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartDKGResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 启动签名请求
type StartSignRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	SessionId       string                        `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 签名会话ID
	KeyId           string                        `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message         []byte                        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // 要签名的消息
	MessageHex      string                        `protobuf:"bytes,4,opt,name=message_hex,json=messageHex,proto3" json:"message_hex,omitempty"` // 消息的hex编码（可选）
	Protocol        string                        `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                       // "gg18", "gg20", "frost"
	Threshold       int32                         `protobuf:"varint,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalNodes      int32                         `protobuf:"varint,7,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	NodeIds         []string                      `protobuf:"bytes,8,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`                            // 参与节点列表
	DerivationPath  string                        `protobuf:"bytes,9,opt,name=derivation_path,json=derivationPath,proto3" json:"derivation_path,omitempty"`       // 派生路径 (e.g. "m/44'/60'/0'/0/0")
	ParentChainCode []byte                        `protobuf:"bytes,10,opt,name=parent_chain_code,json=parentChainCode,proto3" json:"parent_chain_code,omitempty"` // 根 ChainCode，用于派生
	AuthTokens      []*StartSignRequest_AuthToken `protobuf:"bytes,11,rep,name=auth_tokens,json=authTokens,proto3" json:"auth_tokens,omitempty"`
	ClientPublicKey string                        `protobuf:"bytes,12,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"` // Client (P1) 的 Passkey 公钥（hex）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartSignRequest) Reset() {
	*x = StartSignRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest) ProtoMessage() {}

func (x *StartSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest.ProtoReflect.Descriptor instead.
func (*StartSignRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{8}
}

func (x *StartSignRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *StartSignRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *StartSignRequest) GetMessageHex() string {
	if x != nil {
		return x.MessageHex
	}
	return ""
}

func (x *StartSignRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *StartSignRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *StartSignRequest) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *StartSignRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *StartSignRequest) GetDerivationPath() string {
	if x != nil {
		return x.DerivationPath
	}
	return ""
}

func (x *StartSignRequest) GetParentChainCode() []byte {
	if x != nil {
		return x.ParentChainCode
	}
	return nil
}

func (x *StartSignRequest) GetAuthTokens() []*StartSignRequest_AuthToken {
	if x != nil {
		return x.AuthTokens
	}
	return nil
}

func (x *StartSignRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

type StartSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignResponse) Reset() {
	*x = StartSignResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignResponse) ProtoMessage() {}

func (x *StartSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignResponse.ProtoReflect.Descriptor instead.
func (*StartSignResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{9}
}

func (x *StartSignResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *StartSignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{10}
}

func (x *AggregateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`                  // hex encoded
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex encoded
	MessageHash   string                 `protobuf:"bytes,4,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	AggregatedAt  string                 `protobuf:"bytes,5,opt,name=aggregated_at,json=aggregatedAt,proto3" json:"aggregated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AggregateResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AggregateResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AggregateResponse) GetMessageHash() string {
	if x != nil {
		return x.MessageHash
	}
	return ""
}

func (x *AggregateResponse) GetAggregatedAt() string {
	if x != nil {
		return x.AggregatedAt
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SentAt        string                 `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	StatusInfo    map[string]string      `protobuf:"bytes,3,rep,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *HeartbeatRequest) GetStatusInfo() map[string]string {
	if x != nil {
		return x.StatusInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	Instructions  map[string]string      `protobuf:"bytes,3,rep,name=instructions,proto3" json:"instructions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *HeartbeatResponse) GetInstructions() map[string]string {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// 鉴权令牌（WebAuthn）
type StartSignRequest_AuthToken struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PasskeySignature  []byte                 `protobuf:"bytes,1,opt,name=passkey_signature,json=passkeySignature,proto3" json:"passkey_signature,omitempty"`    // WebAuthn Assertion Signature
	AuthenticatorData []byte                 `protobuf:"bytes,2,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"` // WebAuthn AuthData
	ClientDataJson    []byte                 `protobuf:"bytes,3,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`        // WebAuthn ClientDataJSON
	CredentialId      string                 `protobuf:"bytes,4,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`                // WebAuthn Credential ID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartSignRequest_AuthToken) Reset() {
	*x = StartSignRequest_AuthToken{}
	mi := &file_mpc_v1_mpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignRequest_AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignRequest_AuthToken) ProtoMessage() {}

func (x *StartSignRequest_AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_mpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignRequest_AuthToken.ProtoReflect.Descriptor instead.
func (*StartSignRequest_AuthToken) Descriptor() ([]byte, []int) {
	return file_mpc_v1_mpc_proto_rawDescGZIP(), []int{8, 0}
}

func (x *StartSignRequest_AuthToken) GetPasskeySignature() []byte {
	if x != nil {
		return x.PasskeySignature
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *StartSignRequest_AuthToken) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

var File_mpc_v1_mpc_proto protoreflect.FileDescriptor

const file_mpc_v1_mpc_proto_rawDesc = "" +
	"\n" +
	"\x10mpc/v1/mpc.proto\x12\x06mpc.v1\"\x9e\x01\n" +
	"\x1cSubmitProtocolMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"t\n" +
	"\x1dSubmitProtocolMessageResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"next_round\x18\x03 \x01(\x05R\tnextRound\"\xb9\x01\n" +
	"\x14CreateSessionRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11participant_nodes\x18\x05 \x03(\tR\x10participantNodes\"\xfc\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc8\x02\n" +
	"\x15SessionStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12/\n" +
	"\x13participating_nodes\x18\x05 \x03(\tR\x12participatingNodes\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\"\x81\x02\n" +
	"\x0fStartDKGRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\x06 \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\a \x03(\tR\anodeIds\x12*\n" +
	"\x11client_public_key\x18\b \x01(\tR\x0fclientPublicKey\"F\n" +
	"\x10StartDKGResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf8\x04\n" +
	"\x10StartSignRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1f\n" +
	"\vmessage_hex\x18\x04 \x01(\tR\n" +
	"messageHex\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tthreshold\x18\x06 \x01(\x05R\tthreshold\x12\x1f\n" +
	"\vtotal_nodes\x18\a \x01(\x05R\n" +
	"totalNodes\x12\x19\n" +
	"\bnode_ids\x18\b \x03(\tR\anodeIds\x12'\n" +
	"\x0fderivation_path\x18\t \x01(\tR\x0ederivationPath\x12*\n" +
	"\x11parent_chain_code\x18\n" +
	" \x01(\fR\x0fparentChainCode\x12C\n" +
	"\vauth_tokens\x18\v \x03(\v2\".mpc.v1.StartSignRequest.AuthTokenR\n" +
	"authTokens\x12*\n" +
	"\x11client_public_key\x18\f \x01(\tR\x0fclientPublicKey\x1a\xb6\x01\n" +
	"\tAuthToken\x12+\n" +
	"\x11passkey_signature\x18\x01 \x01(\fR\x10passkeySignature\x12-\n" +
	"\x12authenticator_data\x18\x02 \x01(\fR\x11authenticatorData\x12(\n" +
	"\x10client_data_json\x18\x03 \x01(\fR\x0eclientDataJson\x12#\n" +
	"\rcredential_id\x18\x04 \x01(\tR\fcredentialId\"G\n" +
	"\x11StartSignResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x10AggregateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xb2\x01\n" +
	"\x11AggregateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12!\n" +
	"\fmessage_hash\x18\x04 \x01(\tR\vmessageHash\x12#\n" +
	"\raggregated_at\x18\x05 \x01(\tR\faggregatedAt\"\xce\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\tR\x06sentAt\x12I\n" +
	"\vstatus_info\x18\x03 \x03(\v2(.mpc.v1.HeartbeatRequest.StatusInfoEntryR\n" +
	"statusInfo\x1a=\n" +
	"\x0fStatusInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\tR\n" +
	"receivedAt\x12O\n" +
	"\finstructions\x18\x03 \x03(\v2+.mpc.v1.HeartbeatResponse.InstructionsEntryR\finstructions\x1a?\n" +
	"\x11InstructionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z,github.com/SafeMPC/mpc-service/pb/mpc/v1;mpcb\x06proto3"

var (
	file_mpc_v1_mpc_proto_rawDescOnce sync.Once
	file_mpc_v1_mpc_proto_rawDescData []byte
)

func file_mpc_v1_mpc_proto_rawDescGZIP() []byte {
	file_mpc_v1_mpc_proto_rawDescOnce.Do(func() {
		file_mpc_v1_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_v1_mpc_proto_rawDesc), len(file_mpc_v1_mpc_proto_rawDesc)))
	})
	return file_mpc_v1_mpc_proto_rawDescData
}

var file_mpc_v1_mpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_mpc_v1_mpc_proto_goTypes = []any{
	(*SubmitProtocolMessageRequest)(nil),  // 0: mpc.v1.SubmitProtocolMessageRequest
	(*SubmitProtocolMessageResponse)(nil), // 1: mpc.v1.SubmitProtocolMessageResponse
	(*CreateSessionRequest)(nil),          // 2: mpc.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),         // 3: mpc.v1.CreateSessionResponse
	(*SessionStatusRequest)(nil),          // 4: mpc.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil),         // 5: mpc.v1.SessionStatusResponse
	(*StartDKGRequest)(nil),               // 6: mpc.v1.StartDKGRequest
	(*StartDKGResponse)(nil),              // 7: mpc.v1.StartDKGResponse
	(*StartSignRequest)(nil),              // 8: mpc.v1.StartSignRequest
	(*StartSignResponse)(nil),             // 9: mpc.v1.StartSignResponse
	(*AggregateRequest)(nil),              // 10: mpc.v1.AggregateRequest
	(*AggregateResponse)(nil),             // 11: mpc.v1.AggregateResponse
	(*HeartbeatRequest)(nil),              // 12: mpc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 13: mpc.v1.HeartbeatResponse
	(*StartSignRequest_AuthToken)(nil),    // 14: mpc.v1.StartSignRequest.AuthToken
	nil,                                   // 15: mpc.v1.HeartbeatRequest.StatusInfoEntry
	nil,                                   // 16: mpc.v1.HeartbeatResponse.InstructionsEntry
}
var file_mpc_v1_mpc_proto_depIdxs = []int32{
	14, // 0: mpc.v1.StartSignRequest.auth_tokens:type_name -> mpc.v1.StartSignRequest.AuthToken
	15, // 1: mpc.v1.HeartbeatRequest.status_info:type_name -> mpc.v1.HeartbeatRequest.StatusInfoEntry
	16, // 2: mpc.v1.HeartbeatResponse.instructions:type_name -> mpc.v1.HeartbeatResponse.InstructionsEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_mpc_v1_mpc_proto_init() }
func file_mpc_v1_mpc_proto_init() {
	if File_mpc_v1_mpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_v1_mpc_proto_rawDesc), len(file_mpc_v1_mpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mpc_v1_mpc_proto_goTypes,
		DependencyIndexes: file_mpc_v1_mpc_proto_depIdxs,
		MessageInfos:      file_mpc_v1_mpc_proto_msgTypes,
	}.Build()
	File_mpc_v1_mpc_proto = out.File
	file_mpc_v1_mpc_proto_goTypes = nil
	file_mpc_v1_mpc_proto_depIdxs = nil
}
