// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: mpc/v1/service.proto

package mpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                    // gRPC endpoint (e.g., "1.2.3.4:9091")
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 节点公钥（可选，用于验证）
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`            // 支持的协议 (e.g., ["gg18", "gg20"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_mpc_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    bool                   `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 注册过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_mpc_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ResultType    string                 `protobuf:"bytes,3,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"` // "DKG_PUBKEY" or "SIGNATURE"
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                               // hex encoded result
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                     // 对结果的签名（防篡改）
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                             // 如果失败，填错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_mpc_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReportResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportResultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportResultRequest) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *ReportResultRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ReportResultRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_mpc_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReportResultResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type ServiceHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "active", "busy", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatRequest) Reset() {
	*x = ServiceHeartbeatRequest{}
	mi := &file_mpc_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatRequest) ProtoMessage() {}

func (x *ServiceHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceHeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceHeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServiceHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHeartbeatResponse) Reset() {
	*x = ServiceHeartbeatResponse{}
	mi := &file_mpc_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHeartbeatResponse) ProtoMessage() {}

func (x *ServiceHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ServiceHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceHeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_mpc_v1_service_proto protoreflect.FileDescriptor

const file_mpc_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14mpc/v1/service.proto\x12\x06mpc.v1\"\x8d\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"o\n" +
	"\x14RegisterNodeResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\bR\n" +
	"registered\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"\xb6\x01\n" +
	"\x13ReportResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vresult_type\x18\x03 \x01(\tR\n" +
	"resultType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"2\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"J\n" +
	"\x17ServiceHeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\x18ServiceHeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xf9\x01\n" +
	"\x11ManagementService\x12I\n" +
	"\fRegisterNode\x12\x1b.mpc.v1.RegisterNodeRequest\x1a\x1c.mpc.v1.RegisterNodeResponse\x12I\n" +
	"\fReportResult\x12\x1b.mpc.v1.ReportResultRequest\x1a\x1c.mpc.v1.ReportResultResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.mpc.v1.ServiceHeartbeatRequest\x1a .mpc.v1.ServiceHeartbeatResponseB.Z,github.com/SafeMPC/mpc-service/pb/mpc/v1;mpcb\x06proto3"

var (
	file_mpc_v1_service_proto_rawDescOnce sync.Once
	file_mpc_v1_service_proto_rawDescData []byte
)

func file_mpc_v1_service_proto_rawDescGZIP() []byte {
	file_mpc_v1_service_proto_rawDescOnce.Do(func() {
		file_mpc_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_v1_service_proto_rawDesc), len(file_mpc_v1_service_proto_rawDesc)))
	})
	return file_mpc_v1_service_proto_rawDescData
}

var file_mpc_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mpc_v1_service_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),      // 0: mpc.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 1: mpc.v1.RegisterNodeResponse
	(*ReportResultRequest)(nil),      // 2: mpc.v1.ReportResultRequest
	(*ReportResultResponse)(nil),     // 3: mpc.v1.ReportResultResponse
	(*ServiceHeartbeatRequest)(nil),  // 4: mpc.v1.ServiceHeartbeatRequest
	(*ServiceHeartbeatResponse)(nil), // 5: mpc.v1.ServiceHeartbeatResponse
}
var file_mpc_v1_service_proto_depIdxs = []int32{
	0, // 0: mpc.v1.ManagementService.RegisterNode:input_type -> mpc.v1.RegisterNodeRequest
	2, // 1: mpc.v1.ManagementService.ReportResult:input_type -> mpc.v1.ReportResultRequest
	4, // 2: mpc.v1.ManagementService.Heartbeat:input_type -> mpc.v1.ServiceHeartbeatRequest
	1, // 3: mpc.v1.ManagementService.RegisterNode:output_type -> mpc.v1.RegisterNodeResponse
	3, // 4: mpc.v1.ManagementService.ReportResult:output_type -> mpc.v1.ReportResultResponse
	5, // 5: mpc.v1.ManagementService.Heartbeat:output_type -> mpc.v1.ServiceHeartbeatResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpc_v1_service_proto_init() }
func file_mpc_v1_service_proto_init() {
	if File_mpc_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_v1_service_proto_rawDesc), len(file_mpc_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpc_v1_service_proto_goTypes,
		DependencyIndexes: file_mpc_v1_service_proto_depIdxs,
		MessageInfos:      file_mpc_v1_service_proto_msgTypes,
	}.Build()
	File_mpc_v1_service_proto = out.File
	file_mpc_v1_service_proto_goTypes = nil
	file_mpc_v1_service_proto_depIdxs = nil
}
