// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: mpc/v1/signer.proto

package mpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignerService_StartDKG_FullMethodName             = "/mpc.v1.SignerService/StartDKG"
	SignerService_GetDKGStatus_FullMethodName         = "/mpc.v1.SignerService/GetDKGStatus"
	SignerService_StartSign_FullMethodName            = "/mpc.v1.SignerService/StartSign"
	SignerService_GetSignStatus_FullMethodName        = "/mpc.v1.SignerService/GetSignStatus"
	SignerService_RelayProtocolMessage_FullMethodName = "/mpc.v1.SignerService/RelayProtocolMessage"
	SignerService_Participate_FullMethodName          = "/mpc.v1.SignerService/Participate"
	SignerService_Ping_FullMethodName                 = "/mpc.v1.SignerService/Ping"
)

// SignerServiceClient is the client API for SignerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SignerService 由 mpc-signer 实现，供 mpc-service 调用
// 使用 mpc.proto 中定义的消息类型
type SignerServiceClient interface {
	// DKG 相关（使用 mpc.proto 中的 StartDKGRequest/Response）
	StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error)
	GetDKGStatus(ctx context.Context, in *GetDKGStatusRequest, opts ...grpc.CallOption) (*DKGStatusResponse, error)
	// 签名相关（使用 mpc.proto 中的 StartSignRequest/Response）
	StartSign(ctx context.Context, in *StartSignRequest, opts ...grpc.CallOption) (*StartSignResponse, error)
	GetSignStatus(ctx context.Context, in *GetSignStatusRequest, opts ...grpc.CallOption) (*SignStatusResponse, error)
	// Deprecated: Do not use.
	// 协议消息中继（从 Client 通过 Service 中继到 Signer）
	RelayProtocolMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*RelayMessageResponse, error)
	// Client 直连参与 MPC（流式接口，V3 新增）
	Participate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParticipateRequest, ParticipateResponse], error)
	// 健康检查
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type signerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerServiceClient(cc grpc.ClientConnInterface) SignerServiceClient {
	return &signerServiceClient{cc}
}

func (c *signerServiceClient) StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDKGResponse)
	err := c.cc.Invoke(ctx, SignerService_StartDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) GetDKGStatus(ctx context.Context, in *GetDKGStatusRequest, opts ...grpc.CallOption) (*DKGStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DKGStatusResponse)
	err := c.cc.Invoke(ctx, SignerService_GetDKGStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) StartSign(ctx context.Context, in *StartSignRequest, opts ...grpc.CallOption) (*StartSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSignResponse)
	err := c.cc.Invoke(ctx, SignerService_StartSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) GetSignStatus(ctx context.Context, in *GetSignStatusRequest, opts ...grpc.CallOption) (*SignStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignStatusResponse)
	err := c.cc.Invoke(ctx, SignerService_GetSignStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *signerServiceClient) RelayProtocolMessage(ctx context.Context, in *RelayMessageRequest, opts ...grpc.CallOption) (*RelayMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayMessageResponse)
	err := c.cc.Invoke(ctx, SignerService_RelayProtocolMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerServiceClient) Participate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ParticipateRequest, ParticipateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignerService_ServiceDesc.Streams[0], SignerService_Participate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ParticipateRequest, ParticipateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignerService_ParticipateClient = grpc.BidiStreamingClient[ParticipateRequest, ParticipateResponse]

func (c *signerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, SignerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServiceServer is the server API for SignerService service.
// All implementations must embed UnimplementedSignerServiceServer
// for forward compatibility.
//
// SignerService 由 mpc-signer 实现，供 mpc-service 调用
// 使用 mpc.proto 中定义的消息类型
type SignerServiceServer interface {
	// DKG 相关（使用 mpc.proto 中的 StartDKGRequest/Response）
	StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error)
	GetDKGStatus(context.Context, *GetDKGStatusRequest) (*DKGStatusResponse, error)
	// 签名相关（使用 mpc.proto 中的 StartSignRequest/Response）
	StartSign(context.Context, *StartSignRequest) (*StartSignResponse, error)
	GetSignStatus(context.Context, *GetSignStatusRequest) (*SignStatusResponse, error)
	// Deprecated: Do not use.
	// 协议消息中继（从 Client 通过 Service 中继到 Signer）
	RelayProtocolMessage(context.Context, *RelayMessageRequest) (*RelayMessageResponse, error)
	// Client 直连参与 MPC（流式接口，V3 新增）
	Participate(grpc.BidiStreamingServer[ParticipateRequest, ParticipateResponse]) error
	// 健康检查
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedSignerServiceServer()
}

// UnimplementedSignerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServiceServer struct{}

func (UnimplementedSignerServiceServer) StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDKG not implemented")
}
func (UnimplementedSignerServiceServer) GetDKGStatus(context.Context, *GetDKGStatusRequest) (*DKGStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDKGStatus not implemented")
}
func (UnimplementedSignerServiceServer) StartSign(context.Context, *StartSignRequest) (*StartSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSign not implemented")
}
func (UnimplementedSignerServiceServer) GetSignStatus(context.Context, *GetSignStatusRequest) (*SignStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignStatus not implemented")
}
func (UnimplementedSignerServiceServer) RelayProtocolMessage(context.Context, *RelayMessageRequest) (*RelayMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayProtocolMessage not implemented")
}
func (UnimplementedSignerServiceServer) Participate(grpc.BidiStreamingServer[ParticipateRequest, ParticipateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Participate not implemented")
}
func (UnimplementedSignerServiceServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSignerServiceServer) mustEmbedUnimplementedSignerServiceServer() {}
func (UnimplementedSignerServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServiceServer will
// result in compilation errors.
type UnsafeSignerServiceServer interface {
	mustEmbedUnimplementedSignerServiceServer()
}

func RegisterSignerServiceServer(s grpc.ServiceRegistrar, srv SignerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignerService_ServiceDesc, srv)
}

func _SignerService_StartDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).StartDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_StartDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).StartDKG(ctx, req.(*StartDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_GetDKGStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDKGStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).GetDKGStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_GetDKGStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).GetDKGStatus(ctx, req.(*GetDKGStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_StartSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).StartSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_StartSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).StartSign(ctx, req.(*StartSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_GetSignStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).GetSignStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_GetSignStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).GetSignStatus(ctx, req.(*GetSignStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_RelayProtocolMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).RelayProtocolMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_RelayProtocolMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).RelayProtocolMessage(ctx, req.(*RelayMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignerService_Participate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignerServiceServer).Participate(&grpc.GenericServerStream[ParticipateRequest, ParticipateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignerService_ParticipateServer = grpc.BidiStreamingServer[ParticipateRequest, ParticipateResponse]

func _SignerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignerService_ServiceDesc is the grpc.ServiceDesc for SignerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.SignerService",
	HandlerType: (*SignerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDKG",
			Handler:    _SignerService_StartDKG_Handler,
		},
		{
			MethodName: "GetDKGStatus",
			Handler:    _SignerService_GetDKGStatus_Handler,
		},
		{
			MethodName: "StartSign",
			Handler:    _SignerService_StartSign_Handler,
		},
		{
			MethodName: "GetSignStatus",
			Handler:    _SignerService_GetSignStatus_Handler,
		},
		{
			MethodName: "RelayProtocolMessage",
			Handler:    _SignerService_RelayProtocolMessage_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SignerService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Participate",
			Handler:       _SignerService_Participate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mpc/v1/signer.proto",
}
