// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: mpc/v1/signer.proto

package mpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParticipateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // Client Node ID
	ToNodeId      string                 `protobuf:"bytes,3,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`       // Signer Node ID
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                 // tss-lib wire bytes
	MsgType       string                 `protobuf:"bytes,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`            // 消息类型
	Round         int32                  `protobuf:"varint,6,opt,name=round,proto3" json:"round,omitempty"`
	SessionToken  string                 `protobuf:"bytes,7,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // 仅第一条消息需要，用于鉴权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipateRequest) Reset() {
	*x = ParticipateRequest{}
	mi := &file_mpc_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipateRequest) ProtoMessage() {}

func (x *ParticipateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipateRequest.ProtoReflect.Descriptor instead.
func (*ParticipateRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{0}
}

func (x *ParticipateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParticipateRequest) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *ParticipateRequest) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *ParticipateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParticipateRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ParticipateRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ParticipateRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ParticipateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // Signer Node ID
	ToNodeId      string                 `protobuf:"bytes,3,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`       // Client Node ID
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                 // tss-lib wire bytes
	MsgType       string                 `protobuf:"bytes,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Round         int32                  `protobuf:"varint,6,opt,name=round,proto3" json:"round,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipateResponse) Reset() {
	*x = ParticipateResponse{}
	mi := &file_mpc_v1_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipateResponse) ProtoMessage() {}

func (x *ParticipateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipateResponse.ProtoReflect.Descriptor instead.
func (*ParticipateResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{1}
}

func (x *ParticipateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParticipateResponse) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *ParticipateResponse) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *ParticipateResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ParticipateResponse) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ParticipateResponse) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ParticipateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetDKGStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDKGStatusRequest) Reset() {
	*x = GetDKGStatusRequest{}
	mi := &file_mpc_v1_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDKGStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDKGStatusRequest) ProtoMessage() {}

func (x *GetDKGStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDKGStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDKGStatusRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{2}
}

func (x *GetDKGStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DKGStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "completed", "failed"
	CurrentRound  int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	PublicKey     string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 完成后返回（hex）
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DKGStatusResponse) Reset() {
	*x = DKGStatusResponse{}
	mi := &file_mpc_v1_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGStatusResponse) ProtoMessage() {}

func (x *DKGStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGStatusResponse.ProtoReflect.Descriptor instead.
func (*DKGStatusResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{3}
}

func (x *DKGStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DKGStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DKGStatusResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *DKGStatusResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *DKGStatusResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DKGStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetSignStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignStatusRequest) Reset() {
	*x = GetSignStatusRequest{}
	mi := &file_mpc_v1_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignStatusRequest) ProtoMessage() {}

func (x *GetSignStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSignStatusRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{4}
}

func (x *GetSignStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SignStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentRound  int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,4,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"` // 完成后返回（hex）
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignStatusResponse) Reset() {
	*x = SignStatusResponse{}
	mi := &file_mpc_v1_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignStatusResponse) ProtoMessage() {}

func (x *SignStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignStatusResponse.ProtoReflect.Descriptor instead.
func (*SignStatusResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{5}
}

func (x *SignStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SignStatusResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *SignStatusResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *SignStatusResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RelayMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromNodeId      string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`  // "mobile-p1"
	ToNodeId        string                 `protobuf:"bytes,3,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`        // "server-signer-p2"
	MessageData     []byte                 `protobuf:"bytes,4,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"` // tss-lib 序列化的消息
	Round           int32                  `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
	IsBroadcast     bool                   `protobuf:"varint,6,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	Timestamp       string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientSignature []byte                 `protobuf:"bytes,8,opt,name=client_signature,json=clientSignature,proto3" json:"client_signature,omitempty"` // Client (P1) 使用 Passkey 私钥签名（E2E 认证）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayMessageRequest) Reset() {
	*x = RelayMessageRequest{}
	mi := &file_mpc_v1_signer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessageRequest) ProtoMessage() {}

func (x *RelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessageRequest.ProtoReflect.Descriptor instead.
func (*RelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{6}
}

func (x *RelayMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayMessageRequest) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *RelayMessageRequest) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *RelayMessageRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *RelayMessageRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RelayMessageRequest) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

func (x *RelayMessageRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RelayMessageRequest) GetClientSignature() []byte {
	if x != nil {
		return x.ClientSignature
	}
	return nil
}

type RelayMessageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Accepted  bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	MessageId string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// 如果 Signer 有回复消息，直接返回
	ReplyMessage  []byte `protobuf:"bytes,3,opt,name=reply_message,json=replyMessage,proto3" json:"reply_message,omitempty"`
	HasReply      bool   `protobuf:"varint,4,opt,name=has_reply,json=hasReply,proto3" json:"has_reply,omitempty"`
	NextRound     int32  `protobuf:"varint,5,opt,name=next_round,json=nextRound,proto3" json:"next_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayMessageResponse) Reset() {
	*x = RelayMessageResponse{}
	mi := &file_mpc_v1_signer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMessageResponse) ProtoMessage() {}

func (x *RelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMessageResponse.ProtoReflect.Descriptor instead.
func (*RelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{7}
}

func (x *RelayMessageResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RelayMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RelayMessageResponse) GetReplyMessage() []byte {
	if x != nil {
		return x.ReplyMessage
	}
	return nil
}

func (x *RelayMessageResponse) GetHasReply() bool {
	if x != nil {
		return x.HasReply
	}
	return false
}

func (x *RelayMessageResponse) GetNextRound() int32 {
	if x != nil {
		return x.NextRound
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromService   string                 `protobuf:"bytes,1,opt,name=from_service,json=fromService,proto3" json:"from_service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_mpc_v1_signer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{8}
}

func (x *PingRequest) GetFromService() string {
	if x != nil {
		return x.FromService
	}
	return ""
}

func (x *PingRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_mpc_v1_signer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_v1_signer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_mpc_v1_signer_proto_rawDescGZIP(), []int{9}
}

func (x *PongResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PongResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PongResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_mpc_v1_signer_proto protoreflect.FileDescriptor

const file_mpc_v1_signer_proto_rawDesc = "" +
	"\n" +
	"\x13mpc/v1/signer.proto\x12\x06mpc.v1\x1a\x10mpc/v1/mpc.proto\"\xdd\x01\n" +
	"\x12ParticipateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x03 \x01(\tR\btoNodeId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\tR\amsgType\x12\x14\n" +
	"\x05round\x18\x06 \x01(\x05R\x05round\x12#\n" +
	"\rsession_token\x18\a \x01(\tR\fsessionToken\"\xcf\x01\n" +
	"\x13ParticipateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x03 \x01(\tR\btoNodeId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\tR\amsgType\x12\x14\n" +
	"\x05round\x18\x06 \x01(\x05R\x05round\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"4\n" +
	"\x13GetDKGStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc7\x01\n" +
	"\x11DKGStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"5\n" +
	"\x14GetSignStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc7\x01\n" +
	"\x12SignStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x04 \x01(\x05R\vtotalRounds\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x99\x02\n" +
	"\x13RelayMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x03 \x01(\tR\btoNodeId\x12!\n" +
	"\fmessage_data\x18\x04 \x01(\fR\vmessageData\x12\x14\n" +
	"\x05round\x18\x05 \x01(\x05R\x05round\x12!\n" +
	"\fis_broadcast\x18\x06 \x01(\bR\visBroadcast\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12)\n" +
	"\x10client_signature\x18\b \x01(\fR\x0fclientSignature\"\xb2\x01\n" +
	"\x14RelayMessageResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12#\n" +
	"\rreply_message\x18\x03 \x01(\fR\freplyMessage\x12\x1b\n" +
	"\thas_reply\x18\x04 \x01(\bR\bhasReply\x12\x1d\n" +
	"\n" +
	"next_round\x18\x05 \x01(\x05R\tnextRound\"N\n" +
	"\vPingRequest\x12!\n" +
	"\ffrom_service\x18\x01 \x01(\tR\vfromService\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"[\n" +
	"\fPongResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\xfa\x03\n" +
	"\rSignerService\x12=\n" +
	"\bStartDKG\x12\x17.mpc.v1.StartDKGRequest\x1a\x18.mpc.v1.StartDKGResponse\x12F\n" +
	"\fGetDKGStatus\x12\x1b.mpc.v1.GetDKGStatusRequest\x1a\x19.mpc.v1.DKGStatusResponse\x12@\n" +
	"\tStartSign\x12\x18.mpc.v1.StartSignRequest\x1a\x19.mpc.v1.StartSignResponse\x12I\n" +
	"\rGetSignStatus\x12\x1c.mpc.v1.GetSignStatusRequest\x1a\x1a.mpc.v1.SignStatusResponse\x12V\n" +
	"\x14RelayProtocolMessage\x12\x1b.mpc.v1.RelayMessageRequest\x1a\x1c.mpc.v1.RelayMessageResponse\"\x03\x88\x02\x01\x12J\n" +
	"\vParticipate\x12\x1a.mpc.v1.ParticipateRequest\x1a\x1b.mpc.v1.ParticipateResponse(\x010\x01\x121\n" +
	"\x04Ping\x12\x13.mpc.v1.PingRequest\x1a\x14.mpc.v1.PongResponseB.Z,github.com/SafeMPC/mpc-service/pb/mpc/v1;mpcb\x06proto3"

var (
	file_mpc_v1_signer_proto_rawDescOnce sync.Once
	file_mpc_v1_signer_proto_rawDescData []byte
)

func file_mpc_v1_signer_proto_rawDescGZIP() []byte {
	file_mpc_v1_signer_proto_rawDescOnce.Do(func() {
		file_mpc_v1_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_v1_signer_proto_rawDesc), len(file_mpc_v1_signer_proto_rawDesc)))
	})
	return file_mpc_v1_signer_proto_rawDescData
}

var file_mpc_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mpc_v1_signer_proto_goTypes = []any{
	(*ParticipateRequest)(nil),   // 0: mpc.v1.ParticipateRequest
	(*ParticipateResponse)(nil),  // 1: mpc.v1.ParticipateResponse
	(*GetDKGStatusRequest)(nil),  // 2: mpc.v1.GetDKGStatusRequest
	(*DKGStatusResponse)(nil),    // 3: mpc.v1.DKGStatusResponse
	(*GetSignStatusRequest)(nil), // 4: mpc.v1.GetSignStatusRequest
	(*SignStatusResponse)(nil),   // 5: mpc.v1.SignStatusResponse
	(*RelayMessageRequest)(nil),  // 6: mpc.v1.RelayMessageRequest
	(*RelayMessageResponse)(nil), // 7: mpc.v1.RelayMessageResponse
	(*PingRequest)(nil),          // 8: mpc.v1.PingRequest
	(*PongResponse)(nil),         // 9: mpc.v1.PongResponse
	(*StartDKGRequest)(nil),      // 10: mpc.v1.StartDKGRequest
	(*StartSignRequest)(nil),     // 11: mpc.v1.StartSignRequest
	(*StartDKGResponse)(nil),     // 12: mpc.v1.StartDKGResponse
	(*StartSignResponse)(nil),    // 13: mpc.v1.StartSignResponse
}
var file_mpc_v1_signer_proto_depIdxs = []int32{
	10, // 0: mpc.v1.SignerService.StartDKG:input_type -> mpc.v1.StartDKGRequest
	2,  // 1: mpc.v1.SignerService.GetDKGStatus:input_type -> mpc.v1.GetDKGStatusRequest
	11, // 2: mpc.v1.SignerService.StartSign:input_type -> mpc.v1.StartSignRequest
	4,  // 3: mpc.v1.SignerService.GetSignStatus:input_type -> mpc.v1.GetSignStatusRequest
	6,  // 4: mpc.v1.SignerService.RelayProtocolMessage:input_type -> mpc.v1.RelayMessageRequest
	0,  // 5: mpc.v1.SignerService.Participate:input_type -> mpc.v1.ParticipateRequest
	8,  // 6: mpc.v1.SignerService.Ping:input_type -> mpc.v1.PingRequest
	12, // 7: mpc.v1.SignerService.StartDKG:output_type -> mpc.v1.StartDKGResponse
	3,  // 8: mpc.v1.SignerService.GetDKGStatus:output_type -> mpc.v1.DKGStatusResponse
	13, // 9: mpc.v1.SignerService.StartSign:output_type -> mpc.v1.StartSignResponse
	5,  // 10: mpc.v1.SignerService.GetSignStatus:output_type -> mpc.v1.SignStatusResponse
	7,  // 11: mpc.v1.SignerService.RelayProtocolMessage:output_type -> mpc.v1.RelayMessageResponse
	1,  // 12: mpc.v1.SignerService.Participate:output_type -> mpc.v1.ParticipateResponse
	9,  // 13: mpc.v1.SignerService.Ping:output_type -> mpc.v1.PongResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_mpc_v1_signer_proto_init() }
func file_mpc_v1_signer_proto_init() {
	if File_mpc_v1_signer_proto != nil {
		return
	}
	file_mpc_v1_mpc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_v1_signer_proto_rawDesc), len(file_mpc_v1_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpc_v1_signer_proto_goTypes,
		DependencyIndexes: file_mpc_v1_signer_proto_depIdxs,
		MessageInfos:      file_mpc_v1_signer_proto_msgTypes,
	}.Build()
	File_mpc_v1_signer_proto = out.File
	file_mpc_v1_signer_proto_goTypes = nil
	file_mpc_v1_signer_proto_depIdxs = nil
}
