// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/kashguard/go-mpc-wallet/internal/auth"
	"github.com/kashguard/go-mpc-wallet/internal/config"
	"github.com/kashguard/go-mpc-wallet/internal/data/local"
	"github.com/kashguard/go-mpc-wallet/internal/metrics"
	"testing"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitNewServer returns a new Server instance.
func InitNewServer(server config.Server) (*Server, error) {
	db, err := NewDB(server)
	if err != nil {
		return nil, err
	}
	mailer, err := NewMailer(server)
	if err != nil {
		return nil, err
	}
	service, err := NewPush(server, db)
	if err != nil {
		return nil, err
	}
	i18nService, err := NewI18N(server)
	if err != nil {
		return nil, err
	}
	v := NoTest()
	clock := NewClock(v...)
	authService := NewAuthService(server, db, clock)
	localService := local.NewService(server, db, clock)
	metricsService, err := metrics.New(server, db)
	if err != nil {
		return nil, err
	}
	metadataStore := NewMetadataStore(db)
	keyShareStorage, err := NewKeyShareStorage(server)
	if err != nil {
		return nil, err
	}
	manager := NewNodeManager(metadataStore, server)
	grpcClient, err := NewMPCGRPCClient(server, manager)
	if err != nil {
		return nil, err
	}
	engine := NewProtocolEngine(server, grpcClient)
	discovery := NewNodeDiscovery(manager)
	dkgService := NewDKGServiceProvider(metadataStore, keyShareStorage, engine, manager, discovery)
	keyService := NewKeyServiceProvider(metadataStore, keyShareStorage, engine, dkgService)
	client, err := NewRedisClient(server)
	if err != nil {
		return nil, err
	}
	sessionStore := NewSessionStore(client)
	sessionManager := NewSessionManager(metadataStore, sessionStore, server)
	signingService := NewSigningServiceProvider(keyService, engine, sessionManager, discovery)
	coordinatorService := NewCoordinatorServiceProvider(metadataStore, keyService, signingService, sessionManager, manager, discovery, engine)
	participantService := NewParticipantServiceProvider(server, keyShareStorage, engine)
	registry := NewNodeRegistry(manager)
	grpcServer, err := NewGRPCServer(server)
	if err != nil {
		return nil, err
	}
	client2, err := NewGRPCClient(server)
	if err != nil {
		return nil, err
	}
	nodeService := NewNodeService(server)
	grpcCoordinatorService := NewCoordinatorService(server)
	registryService := NewRegistryService()
	heartbeatService := NewHeartbeatService(server, client2)
	heartbeatManager := NewHeartbeatManager()
	serviceDiscovery, err := NewConsulDiscovery(server)
	if err != nil {
		return nil, err
	}
	serviceRegistry := NewServiceRegistry(serviceDiscovery, server)
	mpcDiscovery := NewMPCDiscovery(serviceRegistry, manager, discovery)
	loadBalancer := NewLoadBalancer()
	apiServer := newServerWithComponents(server, db, mailer, service, i18nService, clock, authService, localService, metricsService, keyService, signingService, coordinatorService, participantService, manager, registry, discovery, sessionManager, grpcServer, client2, nodeService, grpcCoordinatorService, registryService, heartbeatService, heartbeatManager, serviceDiscovery, serviceRegistry, mpcDiscovery, loadBalancer)
	return apiServer, nil
}

// InitNewServerWithDB returns a new Server instance with the given DB instance.
// All the other components are initialized via go wire according to the configuration.
func InitNewServerWithDB(server config.Server, db *sql.DB, t ...*testing.T) (*Server, error) {
	mailer, err := NewMailer(server)
	if err != nil {
		return nil, err
	}
	service, err := NewPush(server, db)
	if err != nil {
		return nil, err
	}
	i18nService, err := NewI18N(server)
	if err != nil {
		return nil, err
	}
	clock := NewClock(t...)
	authService := NewAuthService(server, db, clock)
	localService := local.NewService(server, db, clock)
	metricsService, err := metrics.New(server, db)
	if err != nil {
		return nil, err
	}
	metadataStore := NewMetadataStore(db)
	keyShareStorage, err := NewKeyShareStorage(server)
	if err != nil {
		return nil, err
	}
	manager := NewNodeManager(metadataStore, server)
	grpcClient, err := NewMPCGRPCClient(server, manager)
	if err != nil {
		return nil, err
	}
	engine := NewProtocolEngine(server, grpcClient)
	discovery := NewNodeDiscovery(manager)
	dkgService := NewDKGServiceProvider(metadataStore, keyShareStorage, engine, manager, discovery)
	keyService := NewKeyServiceProvider(metadataStore, keyShareStorage, engine, dkgService)
	client, err := NewRedisClient(server)
	if err != nil {
		return nil, err
	}
	sessionStore := NewSessionStore(client)
	sessionManager := NewSessionManager(metadataStore, sessionStore, server)
	signingService := NewSigningServiceProvider(keyService, engine, sessionManager, discovery)
	coordinatorService := NewCoordinatorServiceProvider(metadataStore, keyService, signingService, sessionManager, manager, discovery, engine)
	participantService := NewParticipantServiceProvider(server, keyShareStorage, engine)
	registry := NewNodeRegistry(manager)
	grpcServer, err := NewGRPCServer(server)
	if err != nil {
		return nil, err
	}
	client2, err := NewGRPCClient(server)
	if err != nil {
		return nil, err
	}
	nodeService := NewNodeService(server)
	grpcCoordinatorService := NewCoordinatorService(server)
	registryService := NewRegistryService()
	heartbeatService := NewHeartbeatService(server, client2)
	heartbeatManager := NewHeartbeatManager()
	serviceDiscovery, err := NewConsulDiscovery(server)
	if err != nil {
		return nil, err
	}
	serviceRegistry := NewServiceRegistry(serviceDiscovery, server)
	mpcDiscovery := NewMPCDiscovery(serviceRegistry, manager, discovery)
	loadBalancer := NewLoadBalancer()
	apiServer := newServerWithComponents(server, db, mailer, service, i18nService, clock, authService, localService, metricsService, keyService, signingService, coordinatorService, participantService, manager, registry, discovery, sessionManager, grpcServer, client2, nodeService, grpcCoordinatorService, registryService, heartbeatService, heartbeatManager, serviceDiscovery, serviceRegistry, mpcDiscovery, loadBalancer)
	return apiServer, nil
}

// wire.go:

// serviceSet groups the default set of providers that are required for initing a server
var serviceSet = wire.NewSet(
	newServerWithComponents,
	NewPush,
	NewMailer,
	NewI18N,
	authServiceSet, local.NewService, metrics.New, NewClock,
	mpcServiceSet,
)

var authServiceSet = wire.NewSet(
	NewAuthService, wire.Bind(new(AuthService), new(*auth.Service)),
)

var mpcServiceSet = wire.NewSet(
	NewMetadataStore,
	NewRedisClient,
	NewSessionStore,
	NewKeyShareStorage,
	NewNodeManager,
	NewNodeRegistry,
	NewNodeDiscovery,
	NewSessionManager,

	NewMPCGRPCClient,
	NewMPCGRPCServer,
	NewProtocolEngine,

	NewDKGServiceProvider,
	NewKeyServiceProvider,
	NewSigningServiceProvider,
	NewCoordinatorServiceProvider,
	NewParticipantServiceProvider,

	NewGRPCServer,
	NewGRPCClient,
	NewNodeService,
	NewCoordinatorService,
	NewRegistryService,
	NewHeartbeatService,
	NewHeartbeatManager,

	NewConsulDiscovery,
	NewServiceRegistry,
	NewMPCDiscovery,
	NewLoadBalancer,
)
