// Code generated by go-swagger; DO NOT EDIT.

package m_p_c_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetMpcNodeParams creates a new GetMpcNodeParams object
// no default values defined in spec.
func NewGetMpcNodeParams() GetMpcNodeParams {

	return GetMpcNodeParams{}
}

// GetMpcNodeParams contains all the bound params for the get mpc node operation
// typically these are obtained from a http.Request
//
// swagger:parameters getMpcNode
type GetMpcNodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	NodeID string `param:"nodeId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMpcNodeParams() beforehand.
func (o *GetMpcNodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNodeID, rhkNodeID, _ := route.Params.GetOK("nodeId")
	if err := o.bindNodeID(rNodeID, rhkNodeID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMpcNodeParams) Validate(formats strfmt.Registry) error {
	var res []error

	// nodeId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNodeID binds and validates parameter NodeID from path.
func (o *GetMpcNodeParams) bindNodeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.NodeID = raw

	return nil
}
