// Code generated by go-swagger; DO NOT EDIT.

package m_p_c_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMpcKeysParams creates a new GetMpcKeysParams object
// with the default values initialized.
func NewGetMpcKeysParams() GetMpcKeysParams {

	var (
		// initialize parameters with default values

		limitDefault  = int64(20)
		offsetDefault = int64(0)
	)

	return GetMpcKeysParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetMpcKeysParams contains all the bound params for the get mpc keys operation
// typically these are obtained from a http.Request
//
// swagger:parameters getMpcKeys
type GetMpcKeysParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*过滤区块链类型
	  In: query
	*/
	ChainType *string `query:"chain_type"`
	/*
	  In: query
	  Default: 20
	*/
	Limit *int64 `query:"limit"`
	/*
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*过滤状态
	  In: query
	*/
	Status *string `query:"status"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMpcKeysParams() beforehand.
func (o *GetMpcKeysParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChainType, qhkChainType, _ := qs.GetOK("chain_type")
	if err := o.bindChainType(qChainType, qhkChainType, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatus, qhkStatus, _ := qs.GetOK("status")
	if err := o.bindStatus(qStatus, qhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMpcKeysParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_type
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	// offset
	// Required: false
	// AllowEmptyValue: false

	// status
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainType binds and validates parameter ChainType from query.
func (o *GetMpcKeysParams) bindChainType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ChainType = &raw

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetMpcKeysParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetMpcKeysParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetMpcKeysParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetMpcKeysParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	return nil
}

// bindStatus binds and validates parameter Status from query.
func (o *GetMpcKeysParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Status = &raw

	return nil
}
